common/src/main/scala/gu/msnotifications/ConnectionSettings.scala, common/src/main/scala/gu/msnotifications/NotificationHubClient.scala, common/src/main/scala/gu/msnotifications/RawWindowsRegistration.scala, common/src/main/scala/gu/msnotifications/Responses.scala, common/src/main/scala/gu/msnotifications/package.scala, common/src/main/scala/notifications/providers/NotificationRegistrar.scala, common/src/main/scala/notifications/providers/WindowsNotificationProvider.scala, common/src/test/scala/gu/msnotifications/RawWindowsRegistrationSpec.scala, registration/app/controllers/Main.scala, registration/app/services/NotificationRegistrarSupport.scala, registration/test/MainControllerSpec.scala
Implementing registration and registration update with tags.
w/o topics as for now
=> MAPI-983 - registrations create and update

.gitignore, build.sbt, common/src/main/scala/aws/AWSAsync.scala, common/src/main/scala/aws/AsyncDynamo.scala, common/src/main/scala/aws/DynamoJsonConversions.scala, common/src/main/scala/models/NotificationReport.scala, common/src/main/scala/notifications/providers/WindowsNotificationProvider.scala, common/src/main/scala/tracking/DynamoNotificationReportRepository.scala, common/src/main/scala/tracking/InMemoryNotificationReportRepository.scala, common/src/main/scala/tracking/SentNotificationReportRepository.scala, common/src/test/scala/models/NotificationReportTest.scala, common/src/test/scala/tracking/DynamoNotificationReportRepositorySpec.scala, common/src/test/scala/tracking/DynamoNotificationReportRepositoryTest.scala, project/localdynamodb.scala, project/plugins.sbt, report/app/controllers/Report.scala, report/conf/routes, report/test/controllers/ReportIntegrationSpec.scala
Adds a Dynamodb implementation of NotificationReportRepository
=> Mapi 986 Report Persistence

common/src/main/scala/gu/msnotifications/AzureRawPush.scala, common/src/main/scala/gu/msnotifications/NotificationHubClient.scala, common/src/main/scala/gu/msnotifications/RawWindowsRegistration.scala, common/src/main/scala/gu/msnotifications/Responses.scala, common/src/main/scala/gu/msnotifications/package.scala, common/src/main/scala/notifications/providers/WindowsNotificationProvider.scala, common/src/test/scala/gu/msnotifications/RawWindowsRegistrationSpec.scala, common/src/test/scala/models/WNSTagSpec.scala, common/src/test/scala/notifications/providers/WindowsNotificationProviderSpec.scala, notification/app/services/NotificationSenderSupport.scala, registration/app/services/NotificationRegistrarSupport.scala
Topics in Registration to be sent in RawWindowsRegistration to Azure hub.
=> MAPI-989: send topics as tags to hub

build.sbt, project/localdynamodb.scala
- localdynamodb sbt config attached only to common project and removed testWithDb task.
=> Fix test suite with in-memory dynamo db

backup/deploy.json, backup/src/main/scala/Boot.scala, backup/src/main/scala/batches/Backup.scala, backup/src/main/scala/batches/BackupConfiguration.scala, backup/src/main/scala/batches/Batch.scala, backup/src/universal/conf/bootstrap.sh, build.sbt, common/src/main/scala/gu/msnotifications/NotificationHubClient.scala, common/src/main/scala/gu/msnotifications/NotificationHubJob.scala, common/src/main/scala/gu/msnotifications/NotificationHubJobType.scala, common/src/main/scala/gu/msnotifications/Responses.scala, notification/conf/bootstrap.sh, registration/conf/bootstrap.sh
=> Mapi 900 registration backup

common/src/main/scala/binders/package.scala, common/src/main/scala/gu/msnotifications/package.scala, common/src/main/scala/models/Notification.scala, common/src/main/scala/models/NotificationReport.scala, common/src/main/scala/models/Topic.scala, common/src/main/scala/models/UserId.scala, common/src/main/scala/tracking/DynamoNotificationReportRepository.scala, common/src/main/scala/tracking/InMemoryNotificationReportRepository.scala, common/src/main/scala/tracking/SentNotificationReportRepository.scala, common/src/test/scala/gu/msnotifications/RawWindowsRegistrationSpec.scala, common/src/test/scala/gu/msnotifications/TagSpec.scala, common/src/test/scala/models/NotificationReportTest.scala, common/src/test/scala/notifications/providers/WindowsNotificationProviderSpec.scala, common/src/test/scala/tracking/DynamoNotificationReportRepositorySpec.scala, notification/app/controllers/Main.scala, notification/conf/routes, registration/test/controllers/MainControllerSpec.scala, report/test/controllers/ReportIntegrationSpec.scala
This PR focuses on using UUIDs instead of String wherever possible. I believe it will bring type safety and consistency for our future changes.
=> Mapi 1084 uuid

backup/src/main/scala/batches/Backup.scala, common/src/main/scala/gu/msnotifications/HubFailure.scala, common/src/main/scala/gu/msnotifications/NotificationHubClient.scala, common/src/main/scala/gu/msnotifications/Responses.scala, common/src/test/scala/gu/msnotifications/AtomFeedResponseSpec.scala
This PR focuses on the XML response parsing.
=> Mapi 1084 atom

common/src/main/scala/gu/msnotifications/AzureRawPush.scala, common/src/main/scala/gu/msnotifications/RawWindowsRegistration.scala, common/src/main/scala/gu/msnotifications/Responses.scala, common/src/main/scala/gu/msnotifications/package.scala, common/src/main/scala/models/Topic.scala, common/src/main/scala/models/TopicType.scala, common/src/test/scala/gu/msnotifications/RawWindowsRegistrationSpec.scala, common/src/test/scala/gu/msnotifications/TagSpec.scala
This PR contains the changes that were necessary to get the integration test working. See the list of commits as they are quite varied.
=> Mapi 1084 integration

common/src/main/scala/azure/NotificationHubClient.scala, common/src/main/scala/models/PushResult.scala, notification/app/notification/controllers/Main.scala
- Add traces
- return 201
- test for 201 in the azure client
=> Add return value when sending a notification

backup/src/main/scala/backup/Backup.scala, backup/src/main/scala/backup/Boot.scala, common/src/main/scala/auditor/AuditorWSClient.scala, common/src/main/scala/azure/NotificationHubClient.scala, common/src/main/scala/azure/NotificationHubJob.scala, common/src/main/scala/azure/Responses.scala, common/src/main/scala/azure/WNSRegistrationId.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/azure/Notification.scala, notification/app/notification/services/AzureRawPushConverter.scala, registration/app/registration/controllers/Main.scala
- logger usage improved (named logger according to https://www.playframework.com/documentation/2.3.x/ScalaLogging#Creating-your-own-loggers
- logger level adjusted
- minor scalaz sugaring
=> MAPI-1130 - cleanup loggers

notification/conf/bootstrap.sh, registration/conf/bootstrap.sh, report/conf/bootstrap.sh
it turns out it was a simple misconfiguration.
=> Fix the cloudwatch config

common/src/main/scala/azure/AzureRawPush.scala
=> Changing azure query from an AND to an OR

notification/app/notification/controllers/Main.scala, notification/test/notification/controllers/MainSpec.scala
Whilst we fix the problem, let's stop the bleeding.
=> disable notifications

notification/app/notification/controllers/Main.scala, notification/test/notification/controllers/MainSpec.scala
Reverts guardian/mobile-n10n#49
=> Re-enable notificaitons for w10

notification/conf/bootstrap.sh, registration/conf/bootstrap.sh, report/conf/bootstrap.sh
These were for kibana which we are killing.
=> MAPI-1289 Remove subscriptions filters

common/src/main/scala/azure/HubFailure.scala, common/src/main/scala/error/NotificationsError.scala, common/src/main/scala/models/NotificationReport.scala, common/src/main/scala/providers/Error.scala, common/src/main/scala/providers/ProviderError.scala, common/src/main/scala/tracking/InMemoryNotificationReportRepository.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/PushResult.scala, notification/app/notification/models/package.scala, notification/app/notification/services/Configuration.scala, notification/app/notification/services/NotificationReportRepositorySupport.scala, notification/app/notification/services/NotificationSender.scala, notification/app/notification/services/WindowsNotificationSender.scala, notification/app/notification/services/frontend/FrontendAlerts.scala, notification/app/notification/services/frontend/FrontendAlertsSupport.scala, notification/app/notification/services/frontend/NewsAlert.scala, notification/app/notification/services/package.scala, notification/test/notification/NotificationsFixtures.scala, notification/test/notification/controllers/MainSpec.scala, notification/test/notification/services/WindowsNotificationSenderSpec.scala, notification/test/notification/services/frontend/FrontendAlertsSpec.scala, registration/app/registration/controllers/Main.scala, registration/app/registration/services/NotificationRegistrar.scala, registration/app/registration/services/WindowsNotificationRegistrar.scala, registration/test/registration/controllers/MainControllerSpec.scala, report/app/report/controllers/Report.scala
follows-up: https://github.com/guardian/mobile-n10n/pull/55
=> [MAPI-1291] Call frontend on notification

notification/app/notification/services/Configuration.scala
https://github.com/guardian/mobile-platform/pull/336
=> renamed properties for notifications

common/src/main/scala/aws/AsyncDynamo.scala, notification/app/notification/services/Configuration.scala, notification/app/notification/services/NotificationReportRepositorySupport.scala, notification/test/notification/controllers/MainSpec.scala, report/app/report/controllers/Report.scala, report/app/report/services/Configuration.scala, report/app/report/services/NotificationReportRepositorySupport.scala
@davidfurey @DiegoVazquezNanini 
Still to come: 
Updating duplicated reports in Dynamo
=> [MAPI-1306] use dynamodb for reporting

registration/app/registration/controllers/Main.scala, registration/app/registration/services/topic/TopicValidator.scala, registration/test/registration/controllers/MainControllerSpec.scala
cc @pvighi @alexduf @DiegoVazquezNanini
=> MAPI-1340 - lenient topic validation

common/src/main/scala/azure/NotificationHubClient.scala
Our Windows 10 client recently received bunch of errors caused by failed responses from Notification Hubs. This PR should help us diagnose failed hub requests.
Also removed not used method that gets title from atom feed.
cc @davidfurey @alexduf @DiegoVazquezNanini
=> added error logging to hub client

common/src/main/scala/azure/NotificationHubClient.scala
Windows hub notification does not accept some of our registration requests (especially with longer tags in it). I doubt this PR helps fixing that, but it's worth to have them set correctly
cc @alexduf @davidfurey
=> setting correct Content-Type headers for registration ops

common/src/main/scala/azure/Tags.scala, common/src/main/scala/tracking/SubscriptionTracker.scala, registration/app/registration/services/NotificationRegistrarSupport.scala, registration/app/registration/services/windows/WindowsNotificationRegistrar.scala, registration/test/registration/services/WindowsNotificationRegistrarSpec.scala
- WindowsNotificationRegistrar: moved bits responsible for calculating diffs and communicating with repository to separate class
cc @alexduf @davidfurey
=> MAPI-1381 - FIXME removed for subscription tracking

notification/app/notification/controllers/Main.scala, notification/app/notification/services/frontend/FrontendAlerts.scala
* added reason message to frontend alerts notification sender.
cc @pvighi
=> Improved rejected notification reason message

backup/src/main/resources/logback.xml, backup/src/universal/conf/bootstrap.sh, build.sbt, notification/conf/bootstrap.sh, notification/conf/logback.xml, project/build.properties, project/plugins.sbt, registration/conf/bootstrap.sh, registration/conf/logback.xml, report/conf/bootstrap.sh, report/conf/logback.xml, report/test/report/controllers/ReportIntegrationSpec.scala
* Removed charset asserts in ReportIntegrationSpec since Play 2.5 no longer sends utf-8 as default. 
cc @alexduf @davidfurey
=> MAPI-1421: upgrading to Play 2.5

common/src/main/scala/azure/Base16.scala, common/src/main/scala/azure/Tags.scala, notification/app/notification/services/AzureRawPushConverter.scala, notification/app/notification/services/WindowsNotificationSender.scala, notification/test/notification/NotificationsFixtures.scala, notification/test/notification/services/AzureRawPushConverterSpec.scala, notification/test/notification/services/WindowsNotificationSenderSpec.scala
cc @alexduf @davidfurey @pvighi
=> MAPI-1387: removed additional Base16 topic encoding

common/src/main/scala/azure/Tags.scala, common/src/main/scala/models/UniqueDeviceIdentifier.scala, common/src/test/scala/azure/TagSpec.scala, registration/test/registration/controllers/MainControllerSpec.scala
Fixes duplicate notifications bug for iOS Beta users
=> Keep iOS uuids uppercase when sending to pushy

build.sbt, common/src/main/scala/conf/NotificationConfiguration.scala, common/src/main/scala/models/TopicType.scala, registration/app/registration/services/Configuration.scala, registration/app/registration/services/topic/TopicValidator.scala, registration/test/registration/services/topic/AuditorTopicValidatorSpec.scala
Because the payload to Azure gets to large with more than 200 topics
=> Limit number of topics to 200

common/src/main/scala/tracking/DynamoTopicSubscriptionsRepository.scala, registration/conf/logback.xml
We’re writing much more than expected to dynamodb, this should help us
understand why
=> Increase logging for tracking/dynamodb operations

common/src/main/scala/azure/Tags.scala, common/src/main/scala/models/IosUdid.scala, common/src/main/scala/models/NewsstandUdid.scala, common/src/main/scala/models/Platform.scala, common/src/main/scala/models/TopicType.scala, common/src/main/scala/models/UniqueDeviceIdentifier.scala, common/src/test/scala/azure/TagSpec.scala, registration/app/registration/RegistrationApplicationLoader.scala, registration/app/registration/controllers/Main.scala, registration/app/registration/models/LegacyNewsstandRegistration.scala, registration/app/registration/services/Configuration.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala, registration/app/registration/services/LegacyRegistrationClient.scala, registration/app/registration/services/LegacyRegistrationConverter.scala, registration/app/registration/services/NotificationRegistrarProvider.scala, registration/app/registration/services/RegistrationConverter.scala, registration/app/registration/services/azure/NewsstandNotificationRegistrar.scala, registration/conf/routes
Allows newsstand devices to  register for notifications
Subsequent PR will have changes to notifications microservice to allow sending of newsstand notifications
=> Newsstand Registration

notification/app/notification/controllers/Main.scala, notification/test/notification/controllers/MainSpec.scala
Goal alerts sent some duplicates. Hopefully we can fix this at source at some point and remove this check
=> Refuse to send duplicate notifications

registration/app/registration/controllers/Main.scala, registration/app/registration/services/Configuration.scala, registration/test/registration/controllers/MainControllerSpec.scala
I'm hoping this might fix the CLOSE_WAIT issue
=> Timeout requests after 30 seconds

registration/app/registration/controllers/Main.scala
This forces the ELB to reconnect each time it wants to perform a healthcheck, which ensures that the server is still accepting connections.
=> Force Play to close healthcheck connections

notification/app/notification/models/ios/Notification.scala, notification/test/notification/models/azure/iOSNotificationSpec.scala
This seems to be causing issues for some users.  Disabling until we work out what is causing the problem
=> Disable mutable-content flag

common/src/main/scala/authentication/AuthenticationSupport.scala, common/src/main/scala/models/Notification.scala, common/src/main/scala/models/NotificationType.scala, common/src/main/scala/models/TopicType.scala, common/src/main/scala/models/elections/ElectionResults.scala, common/src/main/scala/tracking/BatchingTopicSubscriptionsRepository.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/android/AndroidMessageTypes.scala, notification/app/notification/models/android/Notification.scala, notification/app/notification/models/ios/MessageTypes.scala, notification/app/notification/models/ios/Notification.scala, notification/app/notification/models/wns/Notification.scala, notification/app/notification/services/Configuration.scala, notification/app/notification/services/azure/APNSPushConverter.scala, notification/app/notification/services/azure/GCMPushConverter.scala, notification/app/notification/services/azure/WNSPushConverter.scala, notification/test/notification/NotificationsFixtures.scala, notification/test/notification/controllers/MainSpec.scala, notification/test/notification/models/azure/AndroidNotificationSpec.scala, notification/test/notification/models/azure/WNSNotificationSpec.scala, notification/test/notification/models/azure/iOSNotificationSpec.scala, report/app/report/controllers/Report.scala
Follow up PR will be required later, but this should allow US team to start testing
=> Elections notifications

common/src/main/scala/models/Registration.scala, common/src/test/scala/azure/RawGCMRegistrationSpec.scala, common/src/test/scala/azure/RawWindowsRegistrationSpec.scala, common/src/test/scala/models/RegistrationSpec.scala, notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/services/Configuration.scala, notification/app/notification/services/azure/APNSEnterpriseSender.scala, registration/app/registration/RegistrationApplicationLoader.scala, registration/app/registration/controllers/Main.scala, registration/app/registration/services/Configuration.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala, registration/app/registration/services/LegacyRegistrationConverter.scala, registration/app/registration/services/NotificationRegistrarProvider.scala, registration/app/registration/services/azure/APNSEnterpriseNotifcationRegistrar.scala, registration/test/registration/controllers/MainControllerSpec.scala, registration/test/registration/controllers/RegistrationsFixtures.scala, registration/test/registration/services/WindowsNotificationRegistrarSpec.scala
iOS have a different certificate for 'enterprise' (internal beta) builds.  So we need to use a different notification hub for these devices.
=> Enterprise notifications

common/src/main/scala/auditor/package.scala, common/src/test/scala/auditor/TimeExpiringAuditorSpec.scala, registration/app/registration/RegistrationApplicationLoader.scala
* Remote validators do not support ElectionResults
* Add auto expiry of us elections results topic
=> Fix elections validator

registration/app/registration/RegistrationApplicationLoader.scala
=> Fix router import election

common/src/main/scala/models/Notification.scala, notification/app/notification/controllers/Main.scala, notification/test/notification/controllers/MainSpec.scala
These were part of an a/b test, we have decided that the weekend-reading format is better.
@maxspencer
=> Send weekend-reading notifications to weekend-round-up too

project/build.properties
=> Upgrade sbt

common/src/main/scala/auditor/package.scala
Assume match isn’t ended if we don’t know.
=> Handle PA failure

notification/app/notification/models/android/Editions.scala, notification/app/notification/services/azure/GCMPushConverter.scala, notification/test/notification/services/azure/GCMPushConverterSpec.scala
This is required by legacy clients
=> Correctly include edition for Android notifications

notification/app/notification/services/azure/APNSPushConverter.scala
This should allow us to send external links (for surveys) to iOS
=> Category should not be ITEM_CATEGORY for external links

scripts/README.md, scripts/notifyiPadUsers.sh
=> Adds the newsstand CP script

registration/app/registration/models/LegacyRegistration.scala, registration/test/registration/models/LegacyRegistrationSpec.scala
This is a temporary workaround that should be removed once android has spread their fix wide enough.
cc @mohammad-haque
=> parse android's version of the legacy topic.

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/ios/Notification.scala, notification/app/notification/services/azure/NewsstandSender.scala, notification/conf/routes, notification/conf/test.sh, notification/test/notification/controllers/MainSpec.scala, notification/test/notification/services/azure/NewsstandSenderTest.scala, scripts/notifyiPadUsers.sh
This is a recreatiion of @davidfurey's PR here:  https://github.com/guardian/mobile-n10n/pull/107. I've done a rebase, fixed some conflicts and tested it out on code. Everything's looking good so we wanna go to prod now..
=> Newsstand notifications

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/services/Configuration.scala
Configures the newsstand notification sender to use the correct endpoint
=> Configure newsstand notifications

report/conf/riff-raff.yaml
=> fix app name in riffraff deploy for report

report/conf/riff-raff.yaml
Some how didn't commit the riffraff change to report
:(
=> correct report riffraff.yaml

backup/src/main/scala/backup/Lambda.scala
It wasn't starting as it couldn't find the credentials
=> lambdas use the EnvironmentVariableCredentialsProvider

backup/cfn.yaml
=> Backup twice a day

notification/app/notification/services/fcm/AndroidConfigConverter.scala, notification/test/notification/services/fcm/AndroidConfigConverterSpec.scala
This is PR 2/3
Only focuses on converting notifications to the android firebase format.
It doesn't send anything yet
=> Convert Android payload to firebase Payload

common/src/main/scala/azure/apns/Alert.scala, common/src/main/scala/utils/CustomApplicationLoader.scala, notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/services/Configuration.scala, notification/app/notification/services/azure/APNSPushConverter.scala, notification/app/notification/services/azure/AzurePushConverter.scala, notification/app/notification/services/azure/GCMPushConverter.scala, notification/app/notification/services/azure/NotificationsHubSender.scala, notification/app/notification/services/fcm/APNSConfigConverter.scala, notification/app/notification/services/fcm/AndroidConfigConverter.scala, notification/app/notification/services/fcm/FCMConfigConverter.scala, notification/app/notification/services/fcm/FCMNotificationSender.scala, notification/app/notification/services/package.scala, notification/conf/application.conf, notification/test/notification/services/fcm/APNSConfigConverterSpec.scala, notification/test/notification/services/fcm/FCMNotificationSenderSpec.scala, registration/conf/logback.xml
_I recommend reading this PR commit per commit._
This is PR 3/3
This sends the notifications to Firebase. Before merging
=> Send notifications to Firebase

project/plugins.sbt
Adding sbt dependency graph for snyk
=> MSS-244: Adding sbt dependency graph for Snyk

build.sbt, project/plugins.sbt
Please review the ignored entries here:
https://app.snyk.io/org/guardian-mobile/project/36f1c54a-4463-4454-8da5-4bd3fc14dfc8?severity=high&severity=medium&severity=low&policy=ignored
=> Synk Vulnerabilities

build.sbt, common/src/main/scala/azure/NotificationHubClient.scala, common/src/test/scala/azure/NotificationHubClientSpec.scala
(and fix our unit test at the same time)
=> MSS-369 Implement retry when azure rejects a notification

notification/app/notification/services/fcm/APNSConfigConverter.scala
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
=> Set notification expiring after 24h and priority to 10

common/src/main/scala/azure/apns/Properties.scala, common/src/main/scala/models/Provider.scala, notification/app/notification/models/android/Keys.scala, notification/app/notification/models/android/Notification.scala, notification/app/notification/models/ios/Keys.scala, notification/app/notification/models/ios/Notification.scala, notification/app/notification/services/azure/APNSPushConverter.scala, notification/app/notification/services/azure/GCMPushConverter.scala, notification/app/notification/services/fcm/APNSConfigConverter.scala, notification/app/notification/services/fcm/AndroidConfigConverter.scala, notification/app/notification/services/fcm/FCMNotificationSender.scala, notification/test/notification/models/azure/AndroidNotificationSpec.scala, notification/test/notification/models/azure/iOSNotificationSpec.scala, notification/test/notification/services/fcm/APNSConfigConverterSpec.scala, notification/test/notification/services/fcm/AndroidConfigConverterSpec.scala, registration/app/registration/services/NotificationRegistrar.scala, registration/app/registration/services/azure/NotificationsHubRegistrar.scala, registration/app/registration/services/fcm/FcmRegistrar.scala, report/test/report/services/NotificationReportEnricherSpec.scala
breaking news, content notifications and football notifications
=> Ensure Unique ID and the provider is passed to devices

registration/app/registration/RegistrationApplicationLoader.scala, registration/app/registration/services/azure/APNSEnterpriseNotifcationRegistrar.scala, registration/app/registration/services/azure/APNSNotificationRegistrar.scala, registration/app/registration/services/azure/GCMNotificationRegistrar.scala, registration/app/registration/services/azure/NewsstandNotificationRegistrar.scala, registration/app/registration/services/azure/NotificationsHubRegistrar.scala, registration/app/registration/services/fcm/FcmRegistrar.scala, registration/test/registration/services/fcm/FcmRegistrarSpec.scala
Just wondering how many calls we send upstream, out of curiosity (and also to keep an eye on it)
=> Add metrics for each read and write access to Azure and Firebase

common/src/main/scala/tracking/DynamoNotificationReportRepository.scala
Page using the queryResult.getLastEvaluatedKey()
=> Mss 487/show all notifications in report period

eventconsumer/src/main/scala/com/gu/notifications/events/DynamoConversion.scala
Appending to a list creates a new list, swapping to prepend (with a reverse if necessary) to make it faster
=> Mss 487 more efficient timing conversions

apnsworker/src/main/scala/apnsworker/Apns.scala, apnsworker/src/main/scala/apnsworker/ApnsClient.scala
Tiny refactoring so `PushyClient` is not leaking outside of the `ApnsClient` class
=> Do not expose PushyClient outside of the ApnsClient class

apnsworker/src/main/scala/apnsworker/models/ApnsException.scala, build.sbt, fcmworker/src/main/scala/fcmworker/Fcm.scala, fcmworker/src/main/scala/fcmworker/FcmClient.scala, fcmworker/src/main/scala/fcmworker/models/FcmConfig.scala, fcmworker/src/main/scala/fcmworker/models/FcmException.scala, fcmworker/src/main/scala/fcmworker/models/payload/Editions.scala, fcmworker/src/main/scala/fcmworker/models/payload/FcmPayload.scala, fcmworker/src/main/scala/fcmworker/models/payload/Keys.scala, fcmworker/src/main/scala/fcmworker/models/payload/MessageTypes.scala, fcmworker/src/test/resources/logback.xml, fcmworker/src/test/scala/fcmworker/models/payload/FcmPayloadSpec.scala
How to use it:
```
val repo: RegistrationRepository = ???
val registrationService: RegistrationService[IO, Stream] = new RegistrationService(repo)
val fcm = new Fcm(registrationService, config)
val notification: Notification = ???
val shards: Seq[Shard] = ???
def report: Pipe[IO, Either[Throwable, FcmSuccess], Unit] = ???
apns
.send(notification, shards)
.through(report)
.compile
.drain
.unsafeRunSync()
```
=> Add Firebase Cloud Messaging worker

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/services/FilteredNotificationSender.scala
The initial dry run was successful, now I want to see how the database handles big queries.
=> Remove filter, and go full dry run mode

notification/app/notification/NotificationApplicationLoader.scala
=> Dry run for all notifications

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/services/FilteredNotificationSender.scala
This allows small notifications to go through our system
=> Turn production ON for low volumes

build.sbt, notification/conf/logback.xml, notification/conf/riff-raff.yaml, registration/conf/logback.xml, registration/conf/riff-raff.yaml, report/conf/logback.xml, report/conf/riff-raff.yaml
Must be merged in before platform changes applied (platform changes include a user data change that depend on the xenial-mobile-kinesis-agent ami
=> MSS-542: Adding AWS Kinesis Agent

notification/app/notification/services/FilteredNotificationSender.scala
Once these two have been deployed and validated:
https://github.com/guardian/mobile-n10n/pull/253
https://github.com/guardian/mobile-n10n/pull/254
=> Push guardian notification up to 10000 registrations

notification/app/notification/controllers/Main.scala, notification/app/notification/models/Push.scala, notification/app/notification/services/FilteredNotificationSender.scala
Reverts guardian/mobile-n10n#257
=> Revert "Bump the threshold high enough to deliver the morning briefing"

notification/app/notification/controllers/Main.scala, notification/app/notification/models/Push.scala, notification/app/notification/services/FilteredNotificationSender.scala
Reverts guardian/mobile-n10n#258
=> Revert "Revert "Bump the threshold high enough to deliver the morning briefing""

notification/app/notification/services/FilteredNotificationSender.scala
=> Bump limit to include morning briefing

notification/app/notification/services/FilteredNotificationSender.scala
Reverts guardian/mobile-n10n#269
Re-enable breaking news through our in-house system
=> Revert "Revert "Activate in-house notifications for breaking news""

notification/app/notification/services/FilteredNotificationSender.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/ApnsConfig.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
This change was already reviewed as part of https://github.com/guardian/mobile-n10n/pull/266
The only difference being this: https://github.com/guardian/mobile-n10n/commit/9c3a8ae2bbf3321d6e4b7361ac78de81fe67ca3e
I have already created the prod configuration key
=> Enable daily edition only

build.sbt, common/src/main/scala/aws/AsyncDynamo.scala, common/src/main/scala/binders/pathbinders/package.scala, common/src/main/scala/binders/querystringbinders/package.scala, common/src/main/scala/models/JsonUtils.scala, common/src/main/scala/models/Notification.scala, common/src/main/scala/models/PlatformStatistics.scala, common/src/main/scala/models/Provider.scala, common/src/main/scala/utils/MobileAwsCredentialsProvider.scala, notification/app/notification/services/FilteredNotificationSender.scala, notification/app/notification/services/frontend/FrontendAlerts.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/cleaning/CleaningClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/NotificationParser.scala, registration/app/registration/models/LegacyRegistration.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala, registration/app/registration/services/topic/TopicValidator.scala, report/app/report/controllers/Report.scala
I've used scalafix to remove unused imports and fix the procedure syntax.
I decided to not include it in the codebase because:
- it's actually a bit fiddly to make it work
- require to disable the "-Xfatal-warnings" compiler feature.
- it slows down the compilation. I think our sbt config is heavy enough as it is
Otherwise scalafix is great, it does what is says on the tin
=> Mss 599 static analysis

build.sbt, eventconsumer/cfn.yaml, eventconsumer/riff-raff.yaml, eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/EnvDependencies.scala, eventconsumer/src/main/scala/com/gu/notifications/events/LocalRun.scala, eventconsumer/src/main/scala/com/gu/notifications/events/Router.scala, eventconsumer/src/main/scala/com/gu/notifications/events/SqsLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/dynamo/DynamoReportUpdater.scala, eventconsumer/src/main/scala/com/gu/notifications/events/sqs/SqsEventReader.scala, project/MergeMimeTypesStrategy.scala
This should only put the athena event statistics into a new column (athena) and if we're happy with it, then we can swap it to events and delete the sqs driven lambda.
There is a next step of adding a trigger for this, but I'll do this after it looks like it runs okay when triggered manually.
=> Testing athena

eventconsumer/cfn.yaml, eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/EnvDependencies.scala
msck takes a long time to run, unnecessarily checking partitions we won't use for this lambda
=> Add partitions not msck

eventconsumer/cfn.yaml, eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala
We don't need to run very frequently, maybe every half hour.
=> Mss 595/schedule athena metrics

common/src/main/scala/aws/AWSAsync.scala, notification/app/notification/controllers/Main.scala
When Play logs the exception the stack trace should hopefully include both the request and error
=> Log the request when there is a failure

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidWorker.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSWorker.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/cleaning/CleaningClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/Apns.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/Fcm.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/WorkerRequestHandlerSpec.scala
This isn't my proudest unit test, I find it very hard to test side effects with fs2. @TBonnin  do you know if I've missed a trick?
I toyed with the idea of using Mockito here, but the test was just becoming unreadable (also, it didn't work).
=> Add worker unit tests

eventconsumer/src/main/scala/com/gu/notifications/events/dynamo/DynamoReportUpdater.scala
Saw a null pointer in logs on line 48 and want more info
=> Refactored to reveal null

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/LocalRun.scala
Shutdown state shouldn't be possible unless there is some out of order execution part I missed or it doesn't restart properly.
=> Logs suggest the client was in shutdown state in Lambda

build.sbt, common/cfn/notification.yaml, common/cfn/registration.yaml, common/cfn/report.yaml, common/cfn/schedule.yaml, notification/conf/riff-raff.yaml, project/plugins.sbt, registration/conf/riff-raff.yaml, report/conf/riff-raff.yaml, schedulelambda/riff-raff.yaml
Moves cloudformation into this repository. 
* Copies the updated cfn templates, changed by: https://github.com/guardian/mobile-platform/pull/602 to this repo
* Updates the riffraff configurations for report, registration, notification and schedule(lambda) to update their own stacks
=> Mss 614/add cloudformation

common/cfn/notification.yaml, notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/controllers/Main.scala, notification/test/notification/controllers/MainSpec.scala
Adds alert to test that newsstand has been published
=> Mss 158/monitor newsstand notifications

common/cfn/notification.yaml
My last merge kind of broke master 
Fix it
=> fix variable that got misnamed

common/cfn/notification.yaml
=> Mss 158/fix broken master 2

common/cfn/notification.yaml
=> Mss 158/fix broken master 3

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/AthenaMetrics.scala
And add the ability to specify start date and end date in the lambda console to backdate data
=> Mss 758 fix notification counts

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala, eventconsumer/src/main/scala/com/gu/notifications/events/AthenaMetrics.scala
Default True for the scheduled execution, and false when manually run
=> Parametrise the re-indexation of the table.

eventconsumer/cfn.yaml
=> Fix cron expression

common/src/main/scala/db/CompositeRegistrationRepository.scala, common/src/main/scala/db/RegistrationService.scala
Alter registrations to write two database. The existing one, and a new one inside the the private subnet
cc: @alexduf (you probably shouldn't be reviewing this )
=> Added a composite repository which writes to two databases

db-cleaner/src/cleaner.rs
This fetches recursively all the parameters under a namespace. Tested on CODE :heavy_check_mark:
=> Recursive fetching of SSM parameters

common/src/main/scala/db/RegistrationService.scala
Database has been re-created, this can now be re-enabled
=> Re-enable dual writing

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidWorker.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSWorker.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/cleaning/CleaningClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/Apns.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/Fcm.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/SqsDeliveryService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Aws.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/NotificationParser.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/WorkerRequestHandlerSpec.scala
I've not worried about perfectly clean code as some of this should be temporary.
Also, what chunk size should we use?
=> Mss 751/segregate token fetching from delivery

common/cfn/notification.yaml
=> Access logs for the notification service

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/WorkerRequestHandlerSpec.scala
=> Re-enable content notificaitons

notificationworkerlambda/topic-counter-cfn.yaml
=> fix cidr  in topic-count lambdda security group

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/WorkerRequestHandlerSpec.scala
Wait until tomorrow to see if everything looks okay
=> Senders for all notifications

notification/app/notification/services/guardian/GuardianNotificationSender.scala
Wait until tomorrow for results of content, but this is next stage of migration to harvester.
=> Harvester for all but breaking news uk

notification/app/notification/services/guardian/GuardianNotificationSender.scala
Wait for global breaking news before merging.
=> All notifications via harvester.

common/src/main/scala/db/RegistrationRepository.scala, common/src/main/scala/db/RegistrationService.scala, common/src/main/scala/db/SqlRegistrationRepository.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/TopicCounter.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/TopicCounterLambda.scala, report/test/report/controllers/ReportIntegrationSpec.scala
Makes the threshold for persiisting registration counts configurable by Stage
=> make the threshold for persisting topic counts configurable

notification/app/notification/NotificationApplicationLoader.scala
=> fix config

api-client/version.sbt, build.sbt
How did bintray publishing ever work??
=> Mss 715/fix bintray package name

notification/app/notification/services/guardian/ReportTopicRegistrationCounter.scala
Platform counts should be removed soon anyway
=> Adopt total count as the platform counts

reportextractor/cfn.yaml, reportextractor/src/main/scala/com/gu/notifications/extractor/Lambda.scala
I've extracted all the files but no one can read them :)
=> Give rights to the ophan account to read the files

api-client/src/main/scala/com/gu/mobile.notifications.client/NextGenApiClient.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Importance.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Payloads.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Topic.scala, api-client/src/test/scala/com/gu/mobile/notifications/client/NextGenApiClientSpec.scala, api-client/version.sbt
Have the api-client send breaking news requests sequentially. 
Need to add la lot of Reads to get the test to work
=> Mss 715/prioritise uk breaking news alerts

common/src/main/scala/db/Registration.scala, common/src/main/scala/models/DeviceToken.scala, common/src/main/scala/models/Registration.scala, registration/app/registration/services/DatabaseRegistrar.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala, registration/app/registration/services/LegacyRegistrationConverter.scala, registration/app/registration/services/NotificationRegistrar.scala, registration/test/registration/services/LegacyNewsstandRegistrationConverterSpec.scala, registration/test/registration/services/LegacyRegistrationConverterSpec.scala
This simplifies the device token model and associated logic
=> Clean migration tech debt

common/src/main/scala/models/Registration.scala, registration/app/registration/controllers/Main.scala, registration/conf/routes
=> Add new clean registration endpoint

api-client/src/main/scala/com/gu/mobile.notifications.client/NextGenApiClient.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Importance.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Payloads.scala, api-client/src/main/scala/com/gu/mobile.notifications.client/models/Topic.scala, api-client/src/test/scala/com/gu/mobile/notifications/client/NextGenApiClientSpec.scala
Reverts guardian/mobile-n10n#410
=> Revert "Mss 715/prioritise uk breaking news alerts"

common/src/main/scala/models/DynamoNotificationReport.scala, common/src/main/scala/models/ExtendedNotificationReport.scala, common/src/main/scala/tracking/DynamoNotificationReportRepository.scala, common/src/main/scala/tracking/InMemoryNotificationReportRepository.scala, common/src/main/scala/tracking/SentNotificationReportRepository.scala, common/src/test/scala/models/NotificationReportTest.scala, common/src/test/scala/tracking/DynamoNotificationReportRepositorySpec.scala, commoneventconsumer/src/main/scala/com/gu/notifications/events/model/DynamoEventAggregation.scala, commoneventconsumer/src/main/scala/com/gu/notifications/events/model/EventAggregation.scala, commoneventconsumer/src/main/scala/com/gu/notifications/events/model/PlatformCount.scala, eventconsumer/src/main/scala/com/gu/notifications/events/model/EventsPerNotification.scala, notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/PushResult.scala, notification/test/notification/NotificationsFixtures.scala, notification/test/notification/controllers/MainSpec.scala, report/app/report/ReportApplicationLoader.scala, report/app/report/controllers/Report.scala, report/test/report/controllers/ReportIntegrationSpec.scala
Reverts guardian/mobile-n10n#428
=> Revert "Simplify Notification Report."

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/models/Push.scala, notification/app/notification/services/NotificationSender.scala, notification/app/notification/services/frontend/FrontendAlerts.scala, notification/app/notification/services/guardian/GuardianNotificationSender.scala, notification/test/notification/NotificationsFixtures.scala, notification/test/notification/controllers/MainSpec.scala, notification/test/notification/services/frontend/FrontendAlertsSpec.scala, notification/test/notification/services/guardian/GuardianNotificationSenderSpec.scala
This is a second take on https://github.com/guardian/mobile-n10n/pull/429 following the incident.
This PR actually didn't cause any issues in the first place but I re-tested it just to be sure.
To be merged on Monday the 7th
=> Remove topic limit

common/src/main/scala/models/Notification.scala, common/src/main/scala/models/NotificationType.scala, common/src/main/scala/models/TopicType.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/CustomProperty.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilder.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/Keys.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilderSpec.scala
This is an extension of https://github.com/guardian/mobile-n10n/pull/443 to add the extra fields that the editions app expects.
=> Add editions notification Payload

common/src/main/scala/models/TopicType.scala
=> Fix edition topic type

notification/app/notification/NotificationApplicationLoader.scala, notification/app/notification/controllers/Schedule.scala, notification/conf/routes, schedulelambda/src/main/scala/com/gu/notificationschedule/Main.scala
Add a new endpoint for scheduling notifications
=> MSS-1055: add scheduling endpoint

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala
Remove the content available flag except for Breaking News and Editions
=> MSS-909: Remove content available flag (except Breaking News)

eventconsumer/cfn.yaml
I'm currently re-organising the bucket to prepare for storing more event types
=> Change where the tokens are fetched

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala
Remove content available flag everywhere (except for editions)
=> MSS-909: Remove content available flag (everywhere)

dynamo.yaml
- also move the table to the on demand billing mode
- get rid of the two alarms as they don't match the billing mode
=> Move the dynamo DB template to the N10N repo

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilder.scala
=> Fix morning briefing without titles

common/src/main/scala/models/Notification.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilderSpec.scala
=> Remove the message for the android edition notification

athena-tables.sql
These views are used to count how many notification were received after a push notification.
However we're about to add new events in the raw table, so the views need to filter to count only the right type of events.
I've already applied this changes manually, this is just to keep our repo up to date
=> Update the query such that this table only shows the received event

notificationworkerlambda/sender-worker-cfn.yaml, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
This won't solve our issue, but it should inform us better onto why we get timeouts.
It also increases the timeout from 45s to 90s
=> Investigate timeouts

notification/app/notification/controllers/Main.scala
Add a logger to the push notification to calculate the amount of milliseconds a notification took to process, enabling us to investigate why an alarm is triggered.
=> MSS-1237: Investigate 500 alarm

README.md
Sorry, thought I could just update the master README but it wouldn't let me.
=> Update the README to include new diagram

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilder.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilderSpec.scala
Reverts guardian/mobile-n10n#482
=> Revert "Set a default title for Android payload and pass a title to iOS payload"

common/src/main/scala/models/Registration.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala, registration/app/registration/services/LegacyRegistrationConverter.scala, registration/test/registration/services/LegacyNewsstandRegistrationConverterSpec.scala, registration/test/registration/services/LegacyRegistrationConverterSpec.scala
~I think this ticket is a one-liner.~ No it's not 😛 
I might have been overboard when creating the tickets
=> Add the appVersion to the registration model

common/src/main/scala/db/Registration.scala, common/src/main/scala/db/SqlRegistrationRepository.scala, common/src/test/scala/db/RegistrationServiceSpec.scala, registration/app/registration/services/DatabaseRegistrar.scala, registration/test/registration/controllers/RegistrationsFixtures.scala, registration/test/registration/db/BuildTierSpec.scala
https://theguardian.atlassian.net/browse/MSS-1384
=> MSS-1384: Store the buildTier into the registration database

common/src/main/scala/db/Registration.scala
=> Use the correct build number in preparation for tomorrow's beta

common/src/main/scala/db/SqlRegistrationRepository.scala, common/src/main/scala/metrics/MetricActor.scala, common/src/main/scala/tracking/NotificationReportRepository.scala, notification/app/notification/authentication/NotificationAuthAction.scala, notification/app/notification/controllers/Main.scala, notification/app/notification/data/DataStore.scala, notification/app/notification/services/FastlyPurge.scala, notification/app/notification/services/frontend/FrontendAlerts.scala, notification/app/notification/services/guardian/GuardianNotificationSender.scala, registration/app/registration/auditor/FootballMatchAuditor.scala, registration/app/registration/controllers/Main.scala, registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala
=> Move to using SLF4J logger directly

build.sbt, common/src/main/scala/db/DatabaseConfig.scala, common/src/main/scala/db/Registration.scala, common/src/main/scala/db/RegistrationService.scala, common/src/main/scala/db/SqlRegistrationRepository.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/cleaning/CleaningClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala, notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala, project/build.properties, project/plugins.sbt
Doobie is our database access library. It relies on Cats and FS2 which are two functional programming libraries.
This Pull Requests focuses on upgrading doobie to the latest version available in order to prepare the project to scala 2.13. This implies upgrading Cats, and indirectly upgrading FS2.
Most of the change are cosmetic (version bump, import change, slight api change)
=> Upgrade doobie

fakebreakingnewslambda/fakebreakingnewslambda-cfn.yaml, notification/conf/notification.yaml, notificationworkerlambda/harvester-cfn.yaml, notificationworkerlambda/sender-worker-cfn.yaml, registration/conf/registration.yaml
=> Add OKActions to alarms

fakebreakingnewslambda/fakebreakingnewslambda-cfn.yaml, notification/conf/notification.yaml, notificationworkerlambda/harvester-cfn.yaml, notificationworkerlambda/sender-worker-cfn.yaml, registration/conf/registration.yaml
Reverts guardian/mobile-n10n#507
Reverting this for now, as it's not behaving as we'd like.
=> Revert "Add OKActions to alarms"

README.md
Small follow-up to https://github.com/guardian/mobile-n10n/pull/515.
=> Mention recently migrated football service in main README

notification/conf/notification.yaml, notification/conf/riff-raff.yaml
Change instance type to t4g.micro
=> Change instance type to t4g.micro

registration/conf/registration.yaml, registration/conf/riff-raff.yaml
This changes the AMI image upon creation of instance.
Now it spins up an instance using the new ARM
=> ammeded recipe to xenial-mobile-ARM

report/conf/report.yaml, report/conf/riff-raff.yaml
Update report instance type to t4g.micro
https://theguardian.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=LIVE&modal=detail&selectedIssue=LIVE-1632
Deploy the change to CODE and make sure the service works fine
Deploy the change to PROD
=> update report instance type to arm

notification/conf/notification.yaml, notification/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#527
Ready for when we want to rollback to the old instance type
=> Revert "Change instance type to t4g.micro"

report/conf/report.yaml, report/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#526
Ready to revert back to old instance
=> Revert "update report instance type to arm"

registration/conf/registration.yaml, registration/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#525
Ready to revert back to the old instance
=> Revert "ammeded recipe to xenial-mobile-ARM"

common/src/main/scala/db/SqlRegistrationRepository.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
Add logs to SQL statement and harvester to help us debug errors we see with database connections.
=> Improve debugging I/O errors on the database in harvester

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
To be able to debug the database I/O errors in harvester, added catch throwable to catch any type of exception that occurs in the process. 
Check logging
No impact on the functionality. Only logging was added
=> catch throwable errors

notification/conf/notification.yaml, notification/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#529
Merge when we want to upgrade to new instance type
=> Revert "Revert "Change notification instance type to t4g.micro""

registration/conf/registration.yaml, registration/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#530
Ready for when we want to upgrade instance to t4g
=> Revert "Revert "update registration instance type to arm""

report/conf/report.yaml, report/conf/riff-raff.yaml
Reverts guardian/mobile-n10n#531
ready for when we want to use 34g instances
=> Revert "Revert "update report instance type to arm""

project/plugins.sbt
=> Add Dependency Graph plugin

project/build.properties
Upgrades SBT version to 1.5.7.
=> SBT 1.5.7 upgrade

docs/architecture/02-database-tuning.md, docs/testing/05-database-tuning.md
Documents results and conclusions about the registrations database tuning.
=> LIVE-4316 Document registrations database tuning and the test results

build.sbt, common/src/main/scala/aws/AWSAsync.scala, common/src/main/scala/aws/DynamoJsonConversions.scala, common/src/main/scala/aws/S3.scala, common/src/main/scala/utils/LruCache.scala, common/src/test/scala/db/RegistrationServiceSpec.scala, commonscheduledynamodb/src/main/scala/com/gu/notificationschedule/dynamo/NotificationSchedulePersistenceImpl.scala, eventconsumer/src/main/scala/com/football/notifications/events/AthenaMetrics.scala, eventconsumer/src/main/scala/com/gu/notifications/events/dynamo/DynamoReportUpdater.scala, fakebreakingnewslambda/src/main/scala/fakebreakingnews/NotificationClient.scala, fakebreakingnewslambda/src/main/scala/fakebreakingnews/TopUkRegularStory.scala, football/src/main/scala/com/gu/mobile/notifications/football/lib/NotificationsApiClient.scala, football/src/main/scala/com/gu/mobile/notifications/football/lib/PaFootballClient.scala, notification/app/notification/data/DataStore.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/TopicCounter.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryException.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala, notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/InvalidTokens.scala, project/build.properties, registration/test/registration/controllers/RegistrationsFixtures.scala, schedulelambda/src/main/scala/com/gu/notificationschedule/cloudwatch/CloudWatch.scala
- Update some dependencies
- SBT to `1.7.1` a2a6b49e6276a0d4b185f147aa2786045ba883d7
- Scala to `2.12.8` 395af10461f4d060f934c28cc896959dd54bf1c9
- Use fast exception ([because normal ones are expensive](https://www.baeldung.com/java-exceptions-performance)) for control flow e9b70014d9f47846786e2087bfef983037c8eccf
=> Update dependencies & small improvement

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/NotificationParser.scala
Add logging to chunked tokens, to help calculate invocation count
Send test notification and see total invocation count
=> Add logging to chunked tokens, to help calculate invocation count

docs/testing/09-rds-instance-class.md
We are exploring ways to improve the performance of our notification delivery pipeline.
We tested the performance of harvester with different RDS instance classes, and summarised the work in a document.
This PR adds the document to the repository. 
No changes to the program code were made in this PR.
=> LIVE-4421 RDS instance classes

docs/testing/10-harvester-batch-size.md
We have tested the performance of harvester with increased batch size / increased shard size.
The PR adds a document which summaries the test result and the findings.
No changes are made to the programs.
=> LIVE-4521 summarise the test with harvester batch size

docs/testing/13-batch-api-calls.md
Adds documentation for the batch api calls experimentation, with the view to promote this to a feature change rather than an experiment.
=> Add documentation for batch api calls experiment

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala
We log metrics for the sender lambdas, including the processing time and processing rate. These metrics are then visualised in a cloudwatch [dashboard](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#dashboards:name=n10n-profiling).
The metrics are used to help us understand system performance and we will begin to rely on them in upcoming experiments.
When looking at the latest metric data there's some, perhaps unexpected, spikes in the processing rate metric. I believe this could be due to logging metrics for a dryRun. During a dry run we make no actual http requests to firebase/apns so the time taken to "process" the notifications is very small.
It's suggested to only log metrics when the notification is not a dryRun.
Example android processing rate including …
=> Log sender metrics only if not a dry run

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala, senderworker/src/main/scala/com/gu/notifications/ec2worker/Configuration.scala
Reverts guardian/mobile-n10n#806
=> Revert "LIVE-4704: Add ec2 url parameter to apns and firebase config"

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
This adds a log event when the multicast message api request has completed. The log event includes the latency of the api call. 
Knowing the latency of the api call itself will help us validate that the function processing rates we're calculating are valid (they're currently much larger than expected).
I actively didn't include the same log event for the latency of the individual notification send because we already have this kind of data via the firebase google cloud console.
I tried to visualise the latency of the multicast message api call via the firebase google cloud console, but the latency appears to be limited to the `SendMessage` endpoint (or the latency shown is aggregated across all push notification endpoints being used, it's not clear).
NB: The latency we can see from the …
=> Log multicast message request latency

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
In https://github.com/guardian/mobile-n10n/pull/807 we started logging the latency of batch requests to firebase. To make an easy/fair comparison between the two firebase apis we use to send notifications, in this PR we add a similar log event for the latency of individual notification send requests.
This change will add a single log event per token we send. Therefore we will collect a lot of data very quickly about the general request latency. My intention is to revert this change by the end of today when we have enough data.
I tested locally, the logs show the new log event:
```
{
"@timestamp": "2022-11-03T11:54:32.51Z",
"@version": "1",
"message": "Individual send request completed",
"logger_name": "com.gu.notifications.worker.delivery.fcm.FcmClient",
"thread_name": …
```
=> Log individual notification request latency

docs/testing/14-topic-messaging.md
No code changes, just documenting some research about topic messaging.
=> Document information on topic messaging

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
We created an [experiment](https://github.com/guardian/mobile-n10n/pull/747) to test if multicast messaging improved the speed of delivering app notifications.
We then introduced a further [change](https://github.com/guardian/mobile-n10n/pull/823) to allow the lambda to concurrently process multiple SQS messages per invocation.
When sending messages in batches, this appears to be _ok_, however, when sending messages using the old API method (`sendAsync`) we run into a problem:
- lambda picks up multiple messages from the queue
- lambda attempts to process all messages concurrently
- lambda attempts to make (max) 10 * 1000 tokens http requests
- we run out of threads and throw an error
Since the change to concurrently process SQS messages we can see a spike in out of memory issues in the …
=> Send all notifications using multicast messaging

build.sbt
Reverts guardian/mobile-n10n#838
=> Revert "Bump logging libraries"

build.sbt
Reverts guardian/mobile-n10n#835
=> Revert "Bump version of firebase-admin to latest"

docs/testing/17-how-firebase-sends-tokens-to-ios-devices.md
No code changes, just documentation.
=> LIVE 4819: document how firebase send tokens to ios devices

.scala-steward.conf, build.sbt, project/plugins.sbt
Don't merge it.  The revert PR is used to restore the branch where the football lambda size problem happened for investigation.
Reverts guardian/mobile-n10n#1069
=> Do not merge: Revert "Revert "Dependency updates 2023-03-14""

build.sbt, project/plugins.sbt
Reverts guardian/mobile-n10n#1180
The harvester failed with class not found exception
=> Revert "chore(deps): Non-AWS dependency updates"

README.md
Include notes on testing in CODE
=> Include notes on testing in README

build.sbt
Disable automated release version update temporarily
=> temporarily disable automated release version update

project/plugins.sbt
=> remove bintray

api-models/README.markdown
update readme on the release process and update the badge
=> update readme on the release process and update the badge

build.sbt
Revert AWS dependency updates from #1272 and #1269
=> Revert AWS dependency updates

build.sbt, project/plugins.sbt
Reverts guardian/mobile-n10n#1278 as we're confident this did not cause the notifications issues
=> Revert "Revert "chore(deps): Non-AWS dependency updates""

cdk/package-lock.json, cdk/yarn.lock, notificationworkerlambda/cdk/package.json, notificationworkerlambda/cdk/yarn.lock
This combines changes from dependabot PRs https://github.com/guardian/mobile-n10n/pull/1264, https://github.com/guardian/mobile-n10n/pull/1265, https://github.com/guardian/mobile-n10n/pull/1266 because there builds are broken from due to not having the correct scopes in the CI environment. 
This has been fixed going forward and this PR is to make it simpler to merge the changes prior to this fix. …
=> Dependabot changes
