guardian/mobile-n10n

common/src/main/scala/auditor/AuditorWSClient.scala
common/src/main/scala/auditor/package.scala
common/src/test/scala/auditor/AuditorWSClientSpec.scala
common/src/test/scala/gu/msnotifications/WNSTagSpec.scala
registration/app/controllers/Main.scala
registration/app/services/Configuration.scala
registration/app/services/topic/TopicValidator.scala
registration/test/controllers/MainControllerSpec.scala
registration/test/services/topic/AuditorTopicValidatorSpec.scala

Topics filtered against auditors before sending registration request to provider.
Still to come in next PRs:
- rename WNSTag to Tag
- return list of topics in response
- update README

MAPI-980 - invalid topics filtering

---

build.sbt
scalastyle-config.xml

Enable scalastyle as a test step, and fix the dynamodb crashing the jvm when running testQuick and testOnly.
Let's agree that if it gets in our way we either modify the xml file or get rid of it completely.

Scalastyle

---

common/src/main/scala/models/Notification.scala
common/src/test/scala/models/NotificationSpec.scala
notification/test/notification/services/AzureRawPushConverterSpec.scala

We actually don't need that field on the new service

remove unused field: shortUrl

---

build.sbt
project/plugins.sbt

Updates sbt-riffraff-artefacts plugin to the latest version and change build.sbt to build the 4 artefacts on one go.

Update sbt-riffraff-artifact and change build.sbt to build all artefacts

---

common/src/main/scala/models/Notification.scala
common/src/main/scala/models/NotificationType.scala
common/src/test/scala/models/NotificationSpec.scala
notification/app/notification/models/azure/Notification.scala
notification/test/notification/models/azure/NotificationSpec.scala

Notification type was wrong for goal alerts.
Note that the notification is just a randomly generated UUID in notification-football. In the legacy system this id is derived from match info (score, match minute, things like that) so that we cannot send the same notification twice for the same goal. 
Maybe before merging this we could make sure we generate goal alerts in a deterministic way from match info to preserve the safety of the legacy notifications.
I think this is also an issue for content alerts and no one complained so this might not be a big problem
see https://theguardian.atlassian.net/browse/MAPI-1390

Fixed notification types

---

common/src/main/scala/azure/Tags.scala
notification/app/notification/services/AzureRawPushConverter.scala
notification/app/notification/services/WindowsNotificationSender.scala
notification/app/notification/services/frontend/FrontendAlerts.scala
notification/app/notification/services/package.scala
notification/test/notification/NotificationsFixtures.scala
notification/test/notification/services/AzureRawPushConverterSpec.scala
notification/test/notification/services/WindowsNotificationSenderSpec.scala
notification/test/notification/services/frontend/FrontendAlertsSpec.scala

* the same notification is sent twice - one with differently encoded topic
* protection against duplicated messages addressed to user added
cc @alexduf @davidfurey

MAPI-1394 - topic encoded in Base16 are sent as separate hub request

---

common/src/test/scala/auditor/AuditorWSClientSpec.scala
common/src/test/scala/azure/NotificationHubClientSpec.scala

I gave up on this - there is serious Akka Streams magic involved there and only valid solution seems to be using other test server with custom test client so that Play App does not have control over AkkaSystem and Materializer
cc @davidfurey @alexduf 
Randomly happening exception:
```
[11:50:20][Step 1/1] [info] Auditor WS Client should
[11:50:20][Step 1/1] [error]   ! query auditor host and return filtered list of topics
[11:50:20][Step 1/1] [error]    java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down. (ActorMaterializerImpl.scala:88)
[11:50:20][Step 1/1] [error] akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:88)
[11:50:20][Step 1/1] [error] …
```

commenting out test using Play Server.withRouter()

---

notification/conf/bootstrap.sh
registration/conf/bootstrap.sh
report/conf/bootstrap.sh

application.conf files stored on mobile-platform containing application secret have to be merged with these in /conf (containing reference to Play 2.5 Application Loader.
Tested on CODE
cc @davidfurey @alexduf @DiegoVazquezNanini

Merging application.conf during deploy

---

common/src/main/scala/azure/apns/APS.scala
notification/app/notification/models/ios/Notification.scala
notification/app/notification/services/azure/APNSPushConverter.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala

The Guardian iOS app expects the alert to be a string, not an object

Fix ios notifications

---

build.sbt
common/src/main/scala/binders/package.scala
common/src/main/scala/models/Platform.scala
common/src/main/scala/models/UniqueDeviceIdentifier.scala
registration/app/registration/controllers/Main.scala
registration/app/registration/services/NotificationRegistrar.scala
registration/app/registration/services/NotificationRegistrarProvider.scala
registration/app/registration/services/azure/NotificationsHubRegistrar.scala
registration/conf/routes
registration/test/registration/controllers/MainControllerSpec.scala
registration/test/registration/services/WindowsNotificationRegistrarSpec.scala

This is primarily to allow us to roll backwards/forwards between pushy and n10n.  
When a device registers to pushy, it will be unregistered from n10n.
When a device registers to n10n, it will be unregistered from pushy.

Add unregister endpoint

---

common/src/main/scala/conf/NotificationConfiguration.scala
common/src/main/scala/tracking/BatchingTopicSubscriptionsRepository.scala
common/src/main/scala/tracking/DynamoTopicSubscriptionsRepository.scala
common/src/main/scala/tracking/InMemoryTopicSubscriptionsRepository.scala
common/src/main/scala/tracking/SubscriptionTracker.scala
common/src/main/scala/tracking/TopicSubscriptionsRepository.scala
common/src/test/scala/tracking/BatchingTopicSubscriptionsRepositorySpec.scala
notification/app/notification/NotificationApplicationLoader.scala
notification/app/notification/services/Configuration.scala
registration/app/registration/RegistrationApplicationLoader.scala
registration/app/registration/services/Configuration.scala
registration/test/registration/services/WindowsNotificationRegistrarSpec.scala

Update topic subscriptions repository every 60s.  This should avoid the flood of dynamodb writes when we send a breaking news alert

Batch topic subscriptions

---

registration/test/registration/controllers/MainControllerSpec.scala

Unregistration is completely async, and does not block the clients request.  This was making the test fail some (most) of the time on Team City.

Fix flakey tests

---

common/src/main/scala/azure/NotificationHubClient.scala
common/src/main/scala/models/NotificationReport.scala
common/src/test/scala/models/NotificationReportTest.scala
common/src/test/scala/tracking/DynamoNotificationReportRepositorySpec.scala
notification/app/notification/services/azure/APNSSender.scala
notification/app/notification/services/azure/GCMSender.scala
notification/app/notification/services/azure/NotificationsHubSender.scala
notification/app/notification/services/azure/WNSSender.scala
notification/test/notification/NotificationsFixtures.scala
notification/test/notification/services/azure/GCMSenderSpec.scala
notification/test/notification/services/azure/WNSSenderSpec.scala
report/test/report/controllers/ReportIntegrationSpec.scala

Include the notification id generated by azure so that we can fetch
telemetry from azure

Add sendersId to notification report

---

registration/app/registration/controllers/Main.scala
registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala
registration/app/registration/services/LegacyRegistrationConverter.scala
registration/app/registration/services/RegistrationConverter.scala
registration/test/registration/controllers/MainControllerSpec.scala

Returning the correct response will allow legacy clients to update
their local list of subscribed topics.

Return correct response for legacy clients

---

notification/app/notification/models/ios/Notification.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala

Reverts guardian/mobile-n10n#99
@fgauchet has decided that enough users have upgraded to the version of iOS that resolves this issue.

Revert "Disable mutable-content flag"

---

common/src/main/scala/models/Notification.scala
common/src/test/scala/models/NotificationSpec.scala
notification/app/notification/services/azure/APNSPushConverter.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala
notification/test/notification/services/azure/GCMPushConverterSpec.scala
notification/test/notification/services/azure/WNSPushConverterSpec.scala

Temporary workaround so that we can send a longer message to android
and iOS

Add iosUseMessage option for content notifications

---

notification/app/notification/models/android/Notification.scala
notification/app/notification/services/azure/GCMPushConverter.scala
notification/test/notification/models/azure/AndroidNotificationSpec.scala
notification/test/notification/services/azure/GCMPushConverterSpec.scala

Including this field causes the app to filter out these notifications because it doesn’t model breaking news as breaking//<edition>

Remove topics field from android breaking news

---

common/src/main/scala/auditor/package.scala

Naturally, the first thing I tried to determine was what are the consequences of using stale values from the cache? It looks like that just means associating an expired topic with a device, and it would stay there until removed by a later update. It looks to me like this should at worst just mean maintaining this association for no reason. 
I don't actually know when device registration/updates happen though so it's not clear to me when it's sensible to expire the data. Default capacity for the cache is 500, so it seems to me I should have some kind of TTL and/or TTI unless I'd like the data to be stale most of the time. 
I made a guess: TTL 5 minutes, TTI 1 minute. Thoughts?
@alexduf @davidfurey

Add LRU cache around is match ended

---

report/app/report/controllers/Report.scala
report/app/report/services/Configuration.scala

This is to grant people access to the reports API without being able to send notifications

Add new reportsOnly api keys

---

scripts/notifyiPadUsers.sh

Script as deployed at present. Remove key if that's the policy (although it was present in the original commit)

Update to current

---

common/src/main/scala/models/Platform.scala

My Bad
This is just a little fix to help us verify that the newsstand notifications works. The 'newsstand' was previously defined as a platform here: https://github.com/guardian/mobile-n10n/blob/master/common/src/main/scala/models/Platform.scala#L9, and I forgot to add this change into the branch that i merged into master. (I'd previously deployed a branch to code with lots of extra debug in which also had this change)
This means we can't verify a registration with the GET /regjstrations route, because when we pass 'newsstand', it causes an error.

add newsstand to platform parameter verification

---

notification/app/notification/services/azure/APNSPushConverter.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala

This is to unblock @aodhol in his task to speedup the ios app when starting from a deeplink.
it should allow ios to use the uri instead of the link.
No client is currently reading the uri so updating it should be safe.

fix deep-link construction

---

notification/app/notification/services/azure/APNSPushConverter.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala

It's apprently simpler for the ios client side to resolve with the full url

send full web url to client side.

---

notification/app/notification/controllers/Main.scala
notification/test/notification/controllers/MainSpec.scala

This was once used to migrate some of our clients, but this isn't
necessary anymore.
It also is pushing us above 20 topics if we receive 20 topics,
triggering a server side error.

remove tag migration

---

common/src/main/scala/aws/AsyncDynamo.scala
common/src/main/scala/utils/MobileAwsCredentialsProvider.scala
notification/app/notification/NotificationApplicationLoader.scala
registration/app/registration/RegistrationApplicationLoader.scala
report/app/report/ReportApplicationLoader.scala

It seems we were still relying on exporting local variables for AWS credentials (deprecated)
This should solve it by getting credentials from the local profile and still work on our EC2 instances

Use custom credential provider to allow running the app locally

---

build.sbt
common/src/main/scala/models/Notification.scala
notification/app/notification/services/azure/APNSPushConverter.scala
notification/app/notification/services/azure/GCMPushConverter.scala
notification/test/notification/models/azure/AndroidNotificationSpec.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala

We store `phase` but try to retrieve `matchStatus`, leading to a deserialisation error.
It's deserialised from the notification payload a client sends to our service (`matchStatus`), then serialised in the database with `phase`, so I kept `matchStatus` in order to keep the same interface for our clients.
As far as I can tell, `phase` was only used when storing the notification in the database. That makes our past football notification unreadable, but we already can't read them. I think it's fine as we mostly store them for audit purposes.

Fix serialisation issue for FootballMatchStatus

---

build.sbt
notification/app/notification/services/fcm/ApnsConfigConverter.scala
notification/test/notification/services/fcm/ApnsConfigConverterSpec.scala

This is branch 1/3
This PR only focuses on converting notifications to the ios firebase payload. It doesn't actually send the notification yet.

Convert iOS payload to firebase Payload

---

build.sbt

Swaps from inconsistent EC2 tags to hopefully consistent ASGs tags for config.

Upgrade to simple-configuration 1.5.0 

---

common/src/main/scala/models/Notification.scala
common/src/test/scala/models/NotificationReportTest.scala
common/src/test/scala/models/NotificationSpec.scala
common/src/test/scala/tracking/DynamoNotificationReportRepositorySpec.scala
notification/app/notification/NotificationApplicationLoader.scala
notification/app/notification/controllers/Main.scala
notification/app/notification/services/Configuration.scala
notification/app/notification/services/azure/APNSPushConverter.scala
notification/app/notification/services/azure/GCMPushConverter.scala
notification/app/notification/services/fcm/APNSConfigConverter.scala
notification/app/notification/services/fcm/AndroidConfigConverter.scala
notification/app/notification/services/fcm/FCMConfigConverter.scala
notification/app/notification/services/fcm/FCMNotificationSender.scala
notification/app/notification/services/frontend/NewsAlert.scala
notification/app/notification/services/package.scala
notification/conf/application.conf
notification/test/notification/NotificationsFixtures.scala
notification/test/notification/controllers/MainSpec.scala
notification/test/notification/models/azure/AndroidNotificationSpec.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala
notification/test/notification/services/azure/APNSPushConverterSpec.scala
notification/test/notification/services/azure/GCMPushConverterSpec.scala
notification/test/notification/services/azure/GCMSenderSpec.scala
notification/test/notification/services/fcm/APNSConfigConverterSpec.scala
notification/test/notification/services/fcm/AndroidConfigConverterSpec.scala
notification/test/notification/services/fcm/FCMNotificationSenderSpec.scala
report/test/report/controllers/ReportIntegrationSpec.scala
report/test/report/services/NotificationReportEnricherSpec.scala

This is the second part of the changes.
Following https://github.com/guardian/mobile-n10n/pull/175 which failed I alread pushed a subset of the changes here: https://github.com/guardian/mobile-n10n/pull/176
The problem we encountered in prod was due to too many topics being sent by the content notification lambda. I've already fixed the client here: https://github.com/guardian/mobile-notifications-api-client/pull/55 and modified Facia and content notification lambda [here](https://github.com/guardian/facia-tool/pull/347) and [here](https://github.com/guardian/mobile-notifications-content/pull/10)
This is the rebased version of what I reverted, I will test on CODE with all notification types

Send notifications to firebase

---

registration/app/registration/controllers/Main.scala
registration/app/registration/services/NotificationRegistrar.scala
registration/app/registration/services/azure/NotificationsHubRegistrar.scala
registration/conf/routes
registration/test/registration/controllers/MainControllerSpec.scala
registration/test/registration/controllers/RegistrationsFixtures.scala

We use to have a unregistration enpoint, driven by the browser id. That's been removed [here](https://github.com/guardian/mobile-n10n/pull/177)
This PR re-instates a similar endpoint, relying on the device token instead.
I also renamed the `lastKnownChannelUri` we had in a few places. It used to make sense back when we supported w10 push notifications, but nowadays `pushToken` makes much more sense

(Re)create an unregistration endpoint

---

common/src/main/scala/azure/Tags.scala
common/src/main/scala/binders/querystringbinders/package.scala
common/src/main/scala/models/IosUdid.scala
common/src/main/scala/models/NewsstandUdid.scala
common/src/main/scala/models/UniqueDeviceIdentifier.scala
common/src/test/scala/azure/TagSpec.scala
registration/app/registration/controllers/Main.scala
registration/app/registration/services/NotificationRegistrar.scala
registration/app/registration/services/azure/NotificationsHubRegistrar.scala
registration/test/registration/controllers/RegistrationsFixtures.scala

This is cherry picked out of the git history.
We don't store the udid anymore, but if a device doesn't register again we may still have their udid.
This allows us to fetch a registration via the udid and potentially delete it using the token ID
cc @jorgeazevedo

Add udid back for the purpose of querying only

---

common/src/main/scala/models/Platform.scala

We went a bit too far when removing windows from our codebase
We still need to be able to parse notification reports

Fixing report parsing

---

notification/app/notification/NotificationApplicationLoader.scala

This used to be used to push notification to the website. The website would then use that event to show a banner at the bottom of the page.
Since Garnett that feature has been unmaintained and broke at some point. We have been getting 503s in our logs for months and dotcom isn't quite sure if they will fix it or not.
So for now I'm disabling it until further notice

Disable the frontend notification

---

common/src/main/scala/tracking/SubscriptionTracker.scala

There is an instance still remaining for the lambda, but that should be okay.
Did I miss any others?

MSS-298: Removing global execution context usage

---

build.sbt
common/src/main/scala/metrics/MetricActor.scala
common/src/main/scala/metrics/MetricDataPoint.scala
common/src/main/scala/metrics/Metrics.scala
common/src/main/scala/utils/CustomApplicationLoader.scala
notification/app/notification/NotificationApplicationLoader.scala
registration/app/registration/RegistrationApplicationLoader.scala
registration/app/registration/services/NotificationRegistrarProvider.scala
registration/test/registration/controllers/RegistrationsFixtures.scala
report/app/report/ReportApplicationLoader.scala

Send metrics about the nature of the registration token. Three cases:
- The registration comes with an Azure token
- The registration comes with a Firebase token
- The registration comes with both
The cloudwatch logic is imported from Mapi. I was considering making a library but I'm actually not sure how relevant that would be for the rest of the department (or even ourselves)

Send token metrics

---

notification/conf/logback.xml
report/conf/logback.xml

ActorSystemImpl is way too verbose and prints every single dropped connection by clients.
We expect connections to drop, especially on mobile, so I set it to only trace on error

Hide log nuisance

---

common/src/main/scala/aws/AsyncDynamo.scala
common/src/main/scala/tracking/DynamoNotificationReportRepository.scala
eventconsumer/src/main/scala/com/gu/notifications/events/S3EventProcessor.scala

Get item is a more natural dynamodb request than query for single item by primary key.
The query statistics will hopefully also be more representative of genuine queries that return a range of results, like listing notifications.
Hopefully, the minimum and average query latencies will noticeably increase after this change.

Mss 426/tidy query for UUID to get

---

eventconsumer/cfn.yaml
eventconsumer/riff-raff.yaml
eventconsumer/src/main/scala/com/gu/notifications/events/AwsClient.scala
eventconsumer/src/main/scala/com/gu/notifications/events/DynamoConversion.scala
eventconsumer/src/main/scala/com/gu/notifications/events/Lambda.scala
eventconsumer/src/main/scala/com/gu/notifications/events/RawEvent.scala
eventconsumer/src/main/scala/com/gu/notifications/events/ReportUpdater.scala
eventconsumer/src/main/scala/com/gu/notifications/events/S3EventModel.scala
eventconsumer/src/main/scala/com/gu/notifications/events/SqsLambda.scala

Write the S3 events into a queue.
The queue is then consumed by a lambda with reservedconcurrency of 1.
Hopefully, this should reduce the collisions substantially, also reducing our read and write overhead consumed capacity.
There may be an outage during the migration, as cloudformation did not like me swapping the notification configuration.
Plan is to do another PR to tidy up the old lambda if this works

MSS-426: Add a queue

---

common/src/main/scala/models/Provider.scala
common/src/main/scala/models/Registration.scala
common/src/test/scala/azure/RawGCMRegistrationSpec.scala
notification/app/notification/models/android/Notification.scala
notification/app/notification/models/ios/Notification.scala
notification/app/notification/services/azure/GCMPushConverter.scala
notification/app/notification/services/fcm/APNSConfigConverter.scala
notification/app/notification/services/fcm/AndroidConfigConverter.scala
notification/app/notification/services/fcm/FCMNotificationSender.scala
notification/test/notification/models/azure/iOSNotificationSpec.scala
registration/app/registration/RegistrationApplicationLoader.scala
registration/app/registration/controllers/Main.scala
registration/app/registration/models/LegacyRegistration.scala
registration/app/registration/services/AzureRegistrarProvider.scala
registration/app/registration/services/LegacyNewsstandRegistrationConverter.scala
registration/app/registration/services/LegacyRegistrationConverter.scala
registration/app/registration/services/MigratingRegistrar.scala
registration/app/registration/services/MigratingRegistrarProvider.scala
registration/app/registration/services/NotificationRegistrar.scala
registration/app/registration/services/NotificationRegistrarProvider.scala
registration/app/registration/services/RegistrarProvider.scala
registration/app/registration/services/azure/NotificationsHubRegistrar.scala
registration/app/registration/services/fcm/FcmRegistrar.scala
registration/test/registration/controllers/RegistrationsFixtures.scala
registration/test/registration/services/LegacyNewsstandRegistrationConverterSpec.scala
registration/test/registration/services/LegacyRegistrationConverterSpec.scala
registration/test/registration/services/MigratingRegistrarProviderSpec.scala
registration/test/registration/services/MigratingRegistrarSpec.scala
report/test/report/services/NotificationReportEnricherSpec.scala

Add provider on the request and the response in order to help the server side decide how to migrate. We can also infer the provider by looking at how many tokens are received.
For ios:
- if we have two tokens, and the provider is Firebase, we now migrate back to Azure
- any other case, we keep registering to azure
For Android:
- no change in the logic, if we have both tokens we migrate the user to firebase (for now)

Stop ios migration

---

commoneventconsumer/src/main/scala/com/gu/notifications/events/model/EventAggregation.scala

Converting the timings was taking upto 7 seconds!
It seems this is because of the repeated rebuilding of the list, so amended to use a mutabe list (ListBuffer) which has a much smaller overhead to build as it doens't have to be rebuilt.

MSS-487: Efficient timing conversion

---

build.sbt
commoneventconsumer/src/main/scala/com/gu/notifications/events/model/EventAggregation.scala
commoneventconsumer/src/main/scala/com/gu/notifications/events/utils/OWritesOps.scala
commoneventconsumer/src/main/scala/com/gu/notifications/events/utils/Percentiles.scala
commoneventconsumer/src/test/scala/com/gu/notifications/events/model/EventAggregationTest.scala
commoneventconsumer/src/test/scala/com/gu/notifications/events/utils/PercentilesTest.scala

Notification report endpoins now returns the timing percentiles rather than a map of all timings 10secs slots

Report: Add timing percentiles

---

registration/app/registration/RegistrationApplicationLoader.scala

Hopefully the order makes more sense now. No change in the code, just `Ctrl`+`x` / `Ctrl`+`v`

Re-organise the registration application loader

---

build.sbt
common/src/main/scala/models/ShardedNotification.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notification/app/notification/services/guardian/ShardedNotification.scala
notification/app/notification/services/guardian/TopicRegistrationCounter.scala
notification/app/notification/services/guardian/TopicStats.scala
notification/test/notification/services/guardian/GuardianNotificationSenderSpec.scala

This code isn't wired so it won't have any impact in production when merged.
I created a class `GuardianNotificationSender` that will write units of work (notification + range) to one SQS queue for one platform.
When we'll wire that class we'll have to create three instances of it: iOS, Android and Newsstand. Both the newsstand and the iOS will share the same SQS queue as the same worker will pick up the work.
I've also ensured the generated ranges are inclusive on both ends [1, 250], [251, 500] such that we can directly use these values in a `between` sql statement.
The payload is of the following format:
```json
{
"notification": {...},
"range": {"start": 1, "end": 250}
}
```
where notification is a serialised `models.Notification`

Write notifications to sqs

---

common/src/main/scala/db/PlatformCount.scala
common/src/main/scala/db/RegistrationRepository.scala
common/src/main/scala/db/RegistrationService.scala
common/src/main/scala/db/SqlRegistrationRepository.scala
common/src/main/scala/models/PlatformCount.scala
common/src/test/scala/db/RegistrationServiceTest.scala
report/app/report/ReportApplicationLoader.scala
report/app/report/controllers/RegistrationCount.scala
report/conf/routes
report/test/report/controllers/RegistrationCountSpec.scala
report/test/report/controllers/ReportIntegrationSpec.scala

The endpoint returns a json:
```json
{
"total": 20,
"ios": 15,
"android": 5,
"newsstand": 0
}
```
The idea of counting per platform is to be able to cache the request on the client side such that for one breaking news we only count once, and use the result twice.

Count registration per topic(s) and platform

---

apnsworker/src/main/scala/apnsworker/models/payload/ApnsPayload.scala
apnsworker/src/test/scala/apnsworker/models/payload/ApnsPayloadSpec.scala

This great document by @jorgeazevedo highlights a missing custom property in the football status payload.

apns payload: add missing 'uri' custom key for football status payload

---

notification/app/notification/NotificationApplicationLoader.scala
notification/app/notification/services/FilteredNotificationSender.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notification/app/notification/services/guardian/ReportTopicRegistrationCounter.scala
notification/test/notification/services/guardian/GuardianNotificationSenderSpec.scala

**This should not be merged until** `create-workers-resources` **is merged**
This wires the code that writes to the SQS queues, and also implements a flip/flop filter that decides where to send the notification

Wire notification to sqs

---

build.sbt
notificationworkerlambda/riff-raff.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/RegistrationCleaningWorker.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/InvalidTokens.scala

Receives events via SQS.
The events aren't sent yet, I'll add that in a subsequent PR

Add registration cleaning worker

---

common/src/main/scala/db/DatabaseConfig.scala
notificationworkerlambda/cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala

- reduce the number of initial connections to 2 per workers, so that a big notification doesn't saturate the database
- bump the retry as the EventSourceMapping needs it to handle messages properly
- treat the delay of the retry as an initial delay applied no matter what

Optimise workers

---

notification/app/notification/NotificationApplicationLoader.scala

Step 1: merge this PR => no traffic on our system anymore
Step 2: flip the dry run mode to off in the config
Step 3: redeploy workers to reload the config => our system is ready to receive notification
Step 4: merge https://github.com/guardian/mobile-n10n/pull/248

Turn dry run off in preparation for production

---

notification/app/notification/services/FilteredNotificationSender.scala

First two notifications were sent (iOS only so far). It's taking a while so I'm bumping the threshold ever so slightly in order to see more notifications, and see if we get them back in our event log.

Add marginally more load

---

notification/app/notification/services/FilteredNotificationSender.scala

So far so good!
The only "issue" i'm seeing so far are connection reset by peer in the pushy client, which I suspect is due to the way lambdas are put to sleep between executions. It doesn't seem to cause any issue other than a warning in the logs

Add more load

---

common/src/main/scala/db/DatabaseConfig.scala
common/src/main/scala/db/RegistrationService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala

I leave the fixed size thread pool to 10, but use a parameter for the maximum amount of database connection.
It is currently set to 10 for services, and 1 for lambdas in the config.

Re organise the database thread pool config

---

notification/app/notification/controllers/Main.scala
notification/app/notification/models/Push.scala
notification/app/notification/services/FilteredNotificationSender.scala

The last increase (10K) didn't bring that many runs (1 @ 6k) as notifications that big are less frequent.
I suggest we now increase it up to tomorrow's morning briefing. As a reminder the breaking news are still being filtered and won't be delivered through our system yet.

Bump the threshold high enough to deliver the morning briefing

---

notificationworkerlambda/platform-worker-cfn.yaml

And bump the retry such that in case of a throttling event, batches are retried.

Raise the concurrency such that throttling is unlikely

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Reporting.scala

We get quite a lot of these, marking them as error leaves a lot of noise in the logs.
We'll eventually disable them completely as this is just normal behaviour, but in the meantime I'm downgrading these "Errors" to warnings so that searching for an Error in the logs is more meaningful

Only mark invalid tokens as warning

---

notificationworkerlambda/platform-worker-cfn.yaml

By doubling the memory last week, we've almost divided the processing time by 2, leading me to believe CPU is actually the current bottleneck.
So I'm increasing the memory size (and by extension the CPU) to the current maximum aws lambdas can take, and I'm looking at the code to see if there's anything that can be done performance wise.

Direct correlation between delivery speed and memory (CPU)

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryException.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala

So we can get the error code in the logs

Adding a trace case for Firebase errors that aren't token errors

---

notificationworkerlambda/platform-worker-cfn.yaml

Not having errors should not be treated as an alarm, so it seems appropriate to set `TreatMissingData` to `notBreaching`
However, not having data is a worry, so adding `TooFewInvocationsAlarm` which will also be set up on CODE, but because we expect this to alarm on CODE I've set ActionsEnabled to false if not prod.

Mss 593/improving lambda cloudwatch alarms

---

notification/app/notification/NotificationApplicationLoader.scala
registration/app/registration/RegistrationApplicationLoader.scala
registration/app/registration/controllers/Main.scala
registration/test/registration/controllers/MainControllerSpec.scala

This is the minimum required change to remove any logic regarding Firebase and Azure registrations.
This doesn't focus on any dead code (yet) but rather focuses on the minimum code change to completely avoid the migration logic and never call any logic from our Azure and Firebase clients.

Remove Firebase and Azure

---

eventconsumer/cfn.yaml

I've segregated the historical from Nov 14th - 28th to `s3://aws-mobile-event-logs-historical/` and create a historical table in athena.

Re-enable lifecycle policy

---

notificationworkerlambda/platform-worker-cfn.yaml

Sometime the alarm wouldn't trigger as the lambda pushes the metrics at the end of the timeout, effectively pushing data in the past.

Fixing alarm following aws support ticket

---

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala

When the lambda errors there might be a bad state indicated here so worth logging.
Also, there's a risk the query is in remaining in QUEUED or RUNNING state. This should make that clear.

MSS-595: Log athena polling states

---

notificationworkerlambda/src/main/resources/logback.xml

It's benign and doesn't bring any value in our logs.

hide connection reset

---

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala
eventconsumer/src/main/scala/com/gu/notifications/events/ScalaAthenaAsyncClient.scala

Not sure where the deadlock is, but swapped most of the Futures to Scala (there's some comments online about deadlock and `thenComposeAsync` although they also suggest that should have been fixed by now). There's an added benefit this segregates the two future types so only one is used in the main logic.
Swapped Thread.sleep to using a scheduled executor service.

Trying Scala futures

---

eventconsumer/src/main/scala/com/gu/notifications/events/AthenaLambda.scala
eventconsumer/src/main/scala/com/gu/notifications/events/AthenaMetrics.scala
eventconsumer/src/main/scala/com/gu/notifications/events/LocalRun.scala
eventconsumer/src/main/scala/com/gu/notifications/events/Router.scala
eventconsumer/src/main/scala/com/gu/notifications/events/SqsLambda.scala
eventconsumer/src/main/scala/com/gu/notifications/events/dynamo/DynamoReportUpdater.scala

After the lamdba runs, it won't be invokved for half an hour.
So we might as well clean up the clients and free up the network connections, etc that the client would otherwise hold.

MSS-595: Recreate clients on each invocation

---

common/src/main/scala/error/Errors.scala
registration/app/registration/services/LegacyRegistrationConverter.scala
registration/test/registration/controllers/MainControllerSpec.scala
registration/test/registration/services/LegacyRegistrationConverterSpec.scala

Deals with special case to handle (android) devices that haven't updated their app in a while and don't have an FCM token. 
@alexduf have I totally misunderstood this?

handle old android devices without firebase token

---

api-client/src/main/scala/com/gu/mobile.notifications.client/ApiClient.scala
api-client/src/main/scala/com/gu/mobile.notifications.client/HttpProvider.scala
api-client/src/main/scala/com/gu/mobile.notifications.client/NextGenApiClient.scala
api-client/src/test/scala/com/gu/mobile/notifications/client/ApiClientSpec.scala
api-client/src/test/scala/com/gu/mobile/notifications/client/NextGenApiClientSpec.scala
api-client/version.sbt
build.sbt

Alters the notifications-api-client to take the api-key as a http header rather than url parameter: See https://theguardian.atlassian.net/browse/MSS-610

Mss 610/update api client with api key header

---

build.sbt
project/plugins.sbt

Publishes apiClient to bintray rather than (not actually publishing it) to sonatype

publish to bintray

---

notification/conf/application.conf

My bad for not testing this change: https://github.com/guardian/mobile-n10n/pull/320 locally
The CSRFfilter consumes any 'Authorization' header, so allow this allows it to be passed on

Mss 610/connfigure csrf filter to accept auth header

---

schedulelambda/src/main/scala/com/gu/notificationschedule/notifications/RequestNotification.scala
schedulelambda/src/test/scala/com/gu/notificationschedule/notifications/RequestNotificationImplSpec.scala

Send the apiKey as a header from schedule tools

send apiKey as a header

---

notification/app/notification/services/guardian/ReportTopicRegistrationCounter.scala

@NathanielBennett I forgot one. This isn't the end of the world as if this HTTP call fails the service assumes the worse case and considers the notification to be a big notification.
I'm testing it on CODE real quick and we should merge that soon after

Fix report authentication

---

notification/app/notification/services/Configuration.scala
registration/app/registration/services/Configuration.scala

Before deleting the keys from SSM, let's ensure they aren't loaded

Remove unused configuration

---

eventconsumer/cfn.yaml

Run every 5 minutes, starting at 2 minutes past the hour. (2, 7, 12, 17...).
2 minutes past the hour to leave fastly 2 minutes to ship the logs

Run event consumer more often

---

common/cfn/notification.yaml

It looks like the failed notification alarms won't trigger as the log group is no longer available.

Fixing newsstand metric namespace

---

common/src/main/scala/db/RegistrationService.scala

So I can delete the database and re-create it with the correct allocated storage and instance size

Disable dual writing

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Env.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/WorkerRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/Apns.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/Fcm.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala

Mostly copy and trim down the worker logic into a sender version.
Sender doesn't need features that use the registration db
Created child classes for Android and IOS
Removed handleEither as we can now just use the new queues.

Segregating worker and sender

---

common/src/main/scala/authentication/AuthAction.scala
notification/app/notification/authentication/NotificationAuthAction.scala
notification/app/notification/controllers/Main.scala
notification/app/notification/services/Configuration.scala
notification/test/notification/controllers/MainSpec.scala
report/app/report/authentication/ReportAuthAction.scala

Need to add Newsstand keys in config before deployment.
After that, logs should indicate if there is a misconfiguration, corrected if necessary and then the next step of applying the restriction can be applied.

MSS-735: Prepare for restricted newsstand api keys

---

notification/app/notification/authentication/NotificationAuthAction.scala
notification/app/notification/services/Configuration.scala
notification/test/notification/controllers/MainSpec.scala

Newsstand keys only for Newsstand. Other keys, not for Newsstand

MSS-735: Segregate key responsibilities for Newsstand

---

notificationworkerlambda/platform-worker-cfn.yaml

So that we retry faster in case of failure

Lower timeout to 45s for the sender lambda

---

common/cfn/registration.yaml

The stddev doesn't appear to be evaluated over a long enough period and aws limits are too low.
Instead, we can swap this for a calculated value based on the last 6 weeks of data.

Swapping stddev metric to a constant

---

api-client/src/main/scala/com/gu/mobile.notifications.client/NextGenApiClient.scala
api-client/src/test/scala/com/gu/mobile/notifications/client/NextGenApiClientSpec.scala

We want to ensure that breaking news alerts can be targeted to our largest arguments. This will done in the notification microservice, so we need to send the breaking news as one request here

send one request for breaking news instead of four

---

common/src/main/scala/db/RegistrationRepository.scala
common/src/main/scala/db/RegistrationService.scala
common/src/main/scala/db/SqlRegistrationRepository.scala
common/src/main/scala/models/ShardedNotification.scala
fakebreakingnewslambda/fakebreakingnewslambda-cfn.yaml
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
report/test/report/controllers/ReportIntegrationSpec.scala

Harvester will need to support both types of shard until notification migrates successfully to send for all platforms.

MSS-805: Allow harvester to support shards for all platforms

---

build.sbt

Rather than copy-pasting our lambda config from one project to another, this extracts the shared config into a function such that the creation of a new lambda shouldn't take us too long.
This is also a first step towards renaming and moving our modules into a more sane hierarchy.
After the refactoring I ran into a deadlock while running the Unit Tests. It seems entirely unrelated and as far as I understand is linked to the way Mockito works. I've user the work around from this issue: https://github.com/sbt/sbt/issues/3022

Simplify lambda projects

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/ApnsConfig.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

Add "Breaking News" in the title for iOS notifications, and directly send the URL instead of the minified one.
Tested on CODE.

Add "Breaking news" and send the mapi URL directly

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryPayload.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilderSpec.scala

This theoretically allows Editorial to re-send a notification that would fix a typo or a headline

Add collapse ID based on article ID or match ID

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala

It turns out the collapse ID is limited to 64 characters, so articles ID can be bigger.

Hash the article ID in a UUID.

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

This is in preparation of the new ios version of the app.
It won't rely on having `content-available: 1` anymore, but will rely on `mutable-content: 1` as a more reliable way to trigger the pre-caching and tracking of push notifications. 🤞

Mutable content is always true to trigger the right background process

---

common/src/main/scala/models/ShardedNotification.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala

This
- remove "platform" from the model passed between the notification service and the harvester. The platform is now fetched from the database for each token
- create a sink for each platform
We currently have only two workers:
- ios (live and daily edition)
- android (live only)
I'm mapping the platforms like that for now:
android => android
android-edition => android
newsstand => ios
ios => ios
ios-edition => ios
We don't have any android-edition or ios-edition in the wild yet so it doesn't matter much, but the next step is deploying specialised workers for each platform.

One sink per platform

---

build.sbt
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/riff-raff.yaml
notificationworkerlambda/sender-worker-cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/ApnsConfig.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

- Add an environment variable to the lambda, telling it which platform it's handling
- Use this platform to decide which configuration to load. This will need to be refactored later such that each lambda has its own SSM prefix based on the platform. This will keep the number of loaded properties to the minimum
- Remove `platform` from the model that gets serialised on the SQS queue
TODO

Instantiate two new lambdas with the same code

---

notificationworkerlambda/sender-worker-cfn.yaml

An alarm was triggered because the new workers haven't got enough invocations.
The new workers are expected to be run once a day, so the period should be a day. I'm extracting the period into a parameter so that each worker can be customised depending on what it processes

Parametrise the period of the "TooFewInvocations" alarms

---

notification/app/notification/NotificationApplicationLoader.scala
notification/app/notification/controllers/Main.scala
notification/app/notification/services/ArticlePurge.scala
notification/app/notification/services/Configuration.scala
notification/app/notification/services/FastlyPurge.scala
notification/test/notification/controllers/MainSpec.scala
notification/test/notification/services/ArticlePurgeSpec.scala

This is to ensure the article that is about to be read is as fresh as possible.
Editorial noticed in some cases the articles had been edited shortly before the notification was sent, but the version visible on the device was an older cached version. This should fix the issue

Purge breaking news article before sending the breaking news

---

db-cleaner/cfn.yaml
db-cleaner/src/cleaner.rs
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/registration-cleaning-worker-cfn.yaml
notificationworkerlambda/sender-worker-cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/topic-counter-cfn.yaml

This refactoring:
- isolate the configuration of each worker. Before it was quite the noodle plate
- this should slightly speed up cold starts as we won't be loading the whole config namespace at boot time anymore
- this also give us the possibility to configure the sender workers independently, such that the ios live and the ios edition workers are executing the same code but two different configs.
Now obvisously that means all the config property are being moved, because of the high chance of manual error I wrote a script to automate the migration. This has been successfully ran on CODE. I'll also keep the older properties for a little while, just in case we need to revert.
Here's the migration script (it's not meant to be pretty)
```bash
#!/usr/bin/env bash
[ -z "$STAGE" ] && echo "set …
```

Refactor the configuration of the workers

---

common/src/main/scala/db/RegistrationRepository.scala
common/src/main/scala/db/RegistrationService.scala
common/src/main/scala/db/SqlRegistrationRepository.scala
common/src/test/scala/db/RegistrationServiceSpec.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
registration/app/registration/services/DatabaseRegistrar.scala
registration/app/registration/services/NotificationRegistrar.scala
registration/test/registration/controllers/RegistrationsFixtures.scala

This is to cover the very unlikely case where a breaking news is sent while a device re-registers.
There is a short window (~60 ms) where a device is deleted from the database before being re-inserted. A selection during that window would be without the token of that device.
To solve that case I'm introducing transactions here, although I haven't been able to measure the impact on performance yet, and it's going to be hard to measure that impact without being in production.

Support transactions while registering

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

Removes all instances of the content-available flag from the iOS push notification payload (except for daily edition)

MSS-909: Remove content-available flag

---

common/src/main/scala/tracking/NotificationReportRepository.scala
commoneventconsumer/src/main/scala/com/gu/notifications/events/model/PlatformCount.scala
eventconsumer/src/main/scala/com/gu/notifications/events/AthenaMetrics.scala

- Modify the SQL request to also count android-edition and ios-edition
- Add attributes to the platform counts
- refactor the method that fetches the reports such that if a report can't be parsed the error is bubbled up to the client

Support notification tracking

---

notification/app/notification/services/ArticlePurge.scala
notification/app/notification/services/Configuration.scala
notification/app/notification/services/FastlyPurge.scala
notification/test/notification/controllers/MainSpec.scala
notification/test/notification/services/ArticlePurgeSpec.scala

This allows a soft purge of a breaking news notification using the surrogate key `Item`. It also adds a timeout of 2 seconds.

MSS-1015: Trigger purge of an article on breaking news with surrogate key

---

notification/app/notification/controllers/Schedule.scala

This allow the editions team to fire a request with the same notification ID twice.
The scheduled notification will automatically be replaced in the dynamoDB (dynamo DB's default is to upsert rows)
Now there's an interesting case I haven't covered here:
- A notification is scheduled for 00:00
- The notification is sent at 00:01
- at 00:02 The same notification ID is re-scheduled for 00:04
- The notification will fail to be sent at 00:04 as it's bearing the same ID and the notification service protects against duplicate push notifications. Is this acceptable @sihil ?
In that case we'd get a bunch of alarms on our end telling us the schedule service failed to send the notification and the notification service encountered a 500. (In other we'll know if this is relevant but users will have …

Make scheduled notification replaceable

---

api-models/src/main/scala/com/gu/mobile.notifications.client/models/Payloads.scala
api-models/src/test/scala/com/gu/mobile/notifications/client/models/PayloadsSpec.scala
fakebreakingnewslambda/src/main/scala/fakebreakingnews/TopUkRegularStory.scala

Managed to neglect payload.scala here: 
:(
https://github.com/guardian/mobile-n10n/pull/462

make title optional in payload

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

Fixes the the kicker bug: Android seems to work fine.
Release at the same tiime as: https://github.com/guardian/mobile-notifications-content/pull/25

set ios title and message

---

common/src/main/scala/db/DatabaseConfig.scala

This should dramatically improve RDS incident recovery.

Force socket timeout to 30 seconds. 

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

So that the daily edition app can properly track which notification has been received.

Add the unique id of the notification to the edition payload

---

reportextractor/src/main/scala/com/gu/notifications/extractor/Lambda.scala

I couldn't find the editions notification in the data lake, that would be why.
Once merged, I'll backdate the last two weeks of data.

Extract editions

---

notificationworkerlambda/src/main/resources/log4j2.xml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala

We're getting closer to understand the reason why Apple rejects some pushes.
I've narrowed it down to these [two lines](https://github.com/relayrides/pushy/blob/master/pushy/src/main/java/com/turo/pushy/apns/ApnsClientHandler.java#L215-L216), but Pushy (or netty) later swallows the exception.
So I've added more debug, and a special logger to only trace that case and avoided polluting our logs too much

Add more log if the future was rejected

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/PushNotificationResponseListenerWithTimeout.scala

While discussing with Frankie yesterday we put our finger onto something:
What if the timeouts we see at the lambda level were caused by APNs not responding for _some_ of the notifications? 
The cause could be a bug in Apple's service, or an unreliable network leading to one of the HTTP/2 channels to be hanging forever. This would mean the netty future would never complete, and therefore our lambda to timeout.
It seems pushy does not implement a per notification timeout: https://github.com/relayrides/pushy/issues/466 which means the hypothesis is at least valid. 
This PR is a fairly naive approach to implement one such timeout. I'm using Java's Timer api as when handling the netty Future we're closer to the imperative Java world than the pure plan of existence that Cats can reach.
We'll …

Implement an individual notification timeout

---

api-models/src/main/scala/com/gu/mobile.notifications.client/models/Topic.scala

Adds a new election topic type to the mobile notifications client, for the benefit of notification emitters (e.g. https://github.com/guardian/facia-tool).

Add 'election' breaking news topic type to mobile notifications client

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilder.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilder.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmPayloadBuilderSpec.scala

iOS notification should never have "The Guardian" as a default title. We now pass whatever title is received, but set a default for Android.

Set a default title for Android payload and pass a title to iOS payload

---

build.sbt

Force jackson-databind and jackson-datatype versions to fix some vulnerability issues:
https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATATYPE-173759
https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-174736
NB: remove after upgrading play app to 2.7 (if we should ever do this)

MSS-1344: Fix jackson vulnerabilites and bump dependencies

---

notification/conf/notification.yaml

I've also added a link to the logs to our dashboard:

Add dashboard link to CloudWatch alerts

---

build.sbt
common/src/main/scala/db/RegistrationRepository.scala
common/src/main/scala/db/RegistrationService.scala
common/src/main/scala/db/SqlRegistrationRepository.scala
notificationworkerlambda/expired-registration-cleaner-cfn.yaml
notificationworkerlambda/riff-raff.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/ExpiredRegistrationCleaner.scala

This replaces the lambda written in Rust that didn't work.
The lambda connects to the database to run a single query to cleanup older registrations

Re-write lambda to cleanup expired registrations

---

notificationworkerlambda/harvester-cfn.yaml

- Reduce the timeout of the lambda to twice the max observed in prod
- Reduce the visibility timeout of the harvester messages to the lambda timeout + 10s such that messages that failed to be processed are re-processed quickly
- Remove the alarm on each lambda error
- Add a new alarm on any message finding its way to the Dead Letter Queue

Improve the alerting of the harvester:

---

build.sbt
notificationworkerlambda/riff-raff.yaml
notificationworkerlambda/sender-worker-cfn.yaml

To help the firebase migration we need to deploy a new set of SQS/Lambda specifically for the android beta population
- Add a new platform for the android beta population
- Fix the `VisibilityTimeout` to be higher than the lambda `Timeout`
- I created the stack in CODE and PROD

Deploy a new android beta worker

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala

Add `mismatched-credential` error message to invalid tokens so they are deleted from the DB.
Tested on CODE

Add mismatched-credential to invalid tokens

---

common/src/main/scala/db/Registration.scala
common/src/test/scala/db/VersionSpec.scala
registration/test/registration/db/BuildTierSpec.scala

Context: this is related to our ongoing problem with our beta users on Android. This should mitigate the issue in the immediate future, and provide a solution once the new beta is released.
All app version bellow build 10000 will be put into the PROD bucket. 
cc @mohammad-haque for your information.
We'll merge that first to put everyone in the PROD bucket, then we'll raise another PR with the correct build number once you've released or are about to release

Adding a version check to the registration service

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala

While fixing this issue I realised our definition of what is `platform` has reached a confusing state. In fact I believe that confusion is what caused this bug in the first place.
I've created a ticket to address that MSS-1539.
Regarding this PR, I introduce a new concept `WorkerSqs` which points to each of our sender workers.
Then I ensured all the routing logic was encapsulated in a single pattern match (see `routeToSqs`) such that we guarantee that a single message won't match two workers.
✅  Tested on CODE

Fix harverster error part 2

---

fakebreakingnewslambda/fakebreakingnewslambda-cfn.yaml
notification/conf/notification.yaml
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/sender-worker-cfn.yaml
registration/conf/registration.yaml

This is a second attempt at https://github.com/guardian/mobile-n10n/pull/507. The only change is [this commit](https://github.com/guardian/mobile-n10n/commit/118af8f567f73d1c5eeb2fd6829e5a6d1233c833), which implements the fix identified [here](https://github.com/guardian/mobile-n10n/pull/507#issuecomment-624580161).

Reinstate automated alarm resolution

---

build.sbt

We're having logging issues in production. I'm not sure when this popped-up again, but it rang a bell.
```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern. 
...
```
It turns out it's an old problem coming back and that we already have the solution. It happens when we assemble a big jar out of multiple smaller jars (the dependencies). Not sure how it worked since we stopped using that `MergeLog4j2PluginCachesStrategy` but now it should work again.
I've also upgraded the logging libraries while I was at it.

Concatenate Log4j2Plugins.dat when packaging

---

build.sbt
common/src/main/scala/metrics/Metrics.scala
common/src/main/scala/models/Notification.scala
common/src/main/scala/utils/CustomApplicationLoader.scala
project/plugins.sbt

Upgrades from Play 2.7.4 to Play 2.8.2. Also upgrades `play-json` to 2.8.1, and `play-json-extensions` to 0.42.0.
Two changes have been made to handle deprecated methods:
1. Switched from `schedule` method to `scheduleWithFixedDelay`. This is in the `CloudWatchMetrics` class, and reflects a change in Akka (which was bumped in 2.8). A description of the new method can be found [here](https://doc.akka.io/docs/akka/current/scheduler.html#schedule-periodically). There's an alternative called `scheduleAtFixedRate` which achieves a slightly different outcome; I'm not sure which more accurately reflects our previous behaviour, but the docs recommend the first if unsure.
2. Used `withFallback` over `++` to merge `ApplicationLoader` configurations. By my understanding, our previous behaviour had …

Bump Play To 2.8.2

---

notification/conf/notification.yaml
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/sender-worker-cfn.yaml
registration/conf/registration.yaml

This makes it easier to take action in response to our alerts. See https://github.com/guardian/google-chat-bots/pull/51 for more details.
The next time these alerts fire they should have a button which links to the relevant runbook.
I've tested this in `CODE`:

Add links to runbook from several alerts

---

api-models/src/main/scala/com/gu/mobile.notifications.client/models/Topic.scala

Adds a new US Election notification topic
Register a device to the new topic and send a test notification

LIVE-951: Add US Election notification topic

---

football/cfn.yaml
football/src/main/scala/com/gu/mobile/notifications/football/lib/DynamoDistinctCheck.scala

Following on from a football notifications alert we received:
https://chat.google.com/room/AAAAEJXWFvQ/grVF4xRW7bc
In future we should be able to debug the assumed Duplicate events better, by logging to info rather than debug. 
Also, in order to get us out of an "in alarm" state, treat the missing data as nonBreaching

Improve Duplicate logging, and treat missing data as notBreaching

---

api-models/version.sbt
build.sbt
project/plugins.sbt

This PR is to move away from bintray and publish the **mobile-notifications-api-models** package to sonatype instead. 
The package was successfully published with version **1.0.12** 
It can be found on Maven https://repo1.maven.org/maven2/com/gu/mobile-notifications-api-models_2.13/1.0.12/
And also can be found in Nexus https://oss.sonatype.org/#nexus-search;quick~mobile-notifications-api-models

Live 1583 bintray to sonatype

---

common/src/main/scala/db/DatabaseConfig.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala

For a while now, we sporadically can't process some shards of a notification. Usually a breaking news notification. We investigated and noticed some I/O errors in the logs of our database.
Full write up to investigation here with @jacobwinch help: https://docs.google.com/document/d/1fLjXzmZ5e3XribxqtZ5E5lEs5N4peQ3QuZoYXrLwKds/edit?ts=5fbcf540#
This PR is to see if shortening our connections help with failed database connections. So instead of leaving a connection open to be reused, everything we need to create a new connection we open and close immediately after processing the notification.
This has been tested in CODE with the help of @marjisound but we will monitor the effects in PROD too after merging.
This was written with @alexduf 
Deploy to CODE and test sending multiple CODE …

Refactor the harvester such that SQL connections are short-lived

---

report/conf/report.yaml

to resolve https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation by making HTTPTokens 'required' when using the EC2 metadata service. Essentially amazon has released a more secure way of fetching metadata and they think that it should be enforced on all instances as the previous approach presented a security risk.
This was tested in CODE

updated report launch config to use IMDSv2

---

registration/conf/registration.yaml

to resolve https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation by making HTTPTokens 'required' when using the EC2 metadata service. Essentially amazon has released a more secure way of fetching metadata and they think that it should be enforced on all instances as the previous approach presented a security risk.
This was tested in CODE

updated registration launch config to use IMDSv2

---

common/src/main/scala/db/DatabaseConfig.scala

Temporarily increase the database execution timeout to 45 seconds, until we have a long term solution in place. There is currently some issues with database connections in the harvester.

Temporarily increase the database execution timeout to 45 seconds

---

notification/conf/notification.yaml

Make HTTPTokens 'required' when using the EC2 metadata service.

Use IMDSv2 metadata service

---

build.sbt
football/src/main/scala/com/gu/mobile/notifications/football/Lambda.scala

Part of the security/vulnerabilities updates for SNYK
mobile-n10n - org.apache.thrift:libthrift@0.13.0 - DoS
Tried updating the ‘parent’ library content-api-client-default (`"com.gu" %% "content-api-client-default" % "17.15"`)
This accorrding to Maven/Sonotype updating content-api-client-default was supposed to update the Apache thriftlib to version 0.14. 
However upon building this did not work:
https://mvnrepository.com/artifact/com.gu/content-api-client-default_2.12/17.2 
- added direct dependancy for this with `"org.apache.thrift" % "libthrift" % apacheThrift,`
To pull out and evict version 0.12 with 0.13
Doc in shared drive: https://docs.google.com/document/d/1stB9KiPFEtjAMOvDjnbN_l9vHYQ4ZQYgQ_H1XXNUsGA/edit
Also see READ ME
- upon checking SNYK at the next deployment the security …

updated dependancy apache:libthrift to 0.13

---

build.sbt
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

Affected versions of this package are vulnerable to Uncontrolled Memory Allocation while decoding a ZlibEncoded byte stream. An attacker could send a large ZlibEncoded byte stream to the Netty server, forcing the server to allocate all of its free memory to a single decoder.
Updated parent Library Firebase to 6.14 to facilitate the upgrade of netty:handler to 4.1.50
The update to parent Library was the minimal to facilitate the upgrade to netty sufficiently

updated parent library firebase-admin to 6.14.0

---

build.sbt

Updates security vulnerabilities as identified through Snyk
Tested in events consumer, schedule and football notifications lambdas by running test and deploying branch to CODE
vulnerabilities will not show up in Snyk

Live-2159: updated and added jackson-databind to version 2.10.5.1

---

build.sbt

Affected versions of this package are vulnerable to Denial of Service (DoS). Unchecked allocation of byte buffer can cause a java.lang.OutOfMemoryError exception.
-**Ran SBT from terminal:**
```
> project notificationworkerlambda + reportextractor + football + schedule + eventconmsumer + fakebreakingnewslambda
> test
```
Also tested in AWS Lambda functions
-**Debug App:**
Sent UK alerts notification through Fronts and succesfully recieved on Debug app
No alert in Snyk to be displayed for this update
Forced the update on top level as the updating of the parent Library is too big and causes breaking changes

Live:2269 updated jackson-dataformat-cbor for Snyk

---

build.sbt

com.google.oauth-client:google-oauth-client is a powerful and easy-to-use Java library for the OAuth 1.0a and OAuth 2.0 authorization standards.
Affected versions of this package are vulnerable to Improper Authorization. PKCE support is not implemented in accordance with the RFC for OAuth 2.0 for Native Apps. Without the use of PKCE, the authorization code returned by an authorization server is not enough to guarantee that the client that issued the initial authorization request is the one that will be authorized. An attacker is able to obtain the authorization code using a malicious app on the client-side and use it to gain authorization to the protected resource.
-**Ran SBT from terminal:** (one at a time)
```
> project notificationworkerlambda + notification
> test
```
-**Debug App:** …

Live-2317: updated google-oauth-client 1.31.0 snyk vulnerability

---

build.sbt

Reverts guardian/mobile-n10n#551
Needs a bit more testing to see what his happening, when merged there were lots of sending failure errors

Revert "Live-2317: updated google-oauth-client 1.31.0 snyk vulnerability"

---

build.sbt

io.netty:netty-codec-http is a network application framework for rapid development of maintainable high performance protocol servers & clients.
Affected versions of this package are vulnerable to HTTP Request Smuggling. It allows an HTTP header that lacks a colon, which might be interpreted as a separate header with an incorrect syntax or as an "invalid fold."
-**Ran SBT from terminal:** (one at a time)
```
> project notificationworkerlambda + reportextractor + football + schedule + eventconmsumer + fakebreakingnewslambda
> test
```
Also tested in AWS Lambda functions
-**Debug App:**
Sent UK alerts notification through Fronts and succesfully recieved on Debug app
No alert in Snyk to be displayed for this update
Forced the update on top level as the updating of the parent Library is too …

Live:2304 - updated: netty-codec-http to 4.1.44

---

notification/conf/riff-raff.yaml
registration/conf/riff-raff.yaml
report/conf/riff-raff.yaml

Ubuntu Xenial is near EOL, and we've had problems with the Xenial AMI on other repos. This bumps us to the more recent Bionic AMI.
There have been similar changes on other repos:
- https://github.com/guardian/mobile-apps-api/pull/1712
- https://github.com/guardian/apps-rendering/pull/1301
FYI @philmcmahon
- Migrate from ubuntu xenial to bionic AMI
(copied PR description from https://github.com/guardian/mobile-entry/pull/42)

Change ami recipe to use bionic bake instead of xenial

---

notification/conf/notification.yaml

This PR removes the public IPv4 address from the EC2 instances. This change would resolve the relevant security issue in AWS security Hub.
Find more info in https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-9-remediation
Deployed and tested in code

LIVE-2059 - notification - Set associatePublicIpAddress to false

---

registration/conf/registration.yaml

This PR removes the public IPv4 address from the EC2 instances. This change would resolve the relevant security issue in AWS security Hub.
Find more info in https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-9-remediation
Deployed and tested in code

LIVE-2061 - registration - Set AssociatePublicIpAddress to false

---

report/conf/report.yaml

This PR sets removes the public IPv4 address from the EC2 instances. This change would resolve the relevant security issue in AWS security Hub.
Find more info in https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-9-remediation
Deployed and tested in code

LIVE-2060 - report - Set AssociatePublicIpAddress to false

---

build.sbt
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala

Reverts guardian/mobile-n10n#553
The lambda deployment failed, so have to revert the change

Revert "Bump Firebase Admin To `6.16.0`"

---

build.sbt
deploy.sh
notificationworkerlambda/ecr.yaml
notificationworkerlambda/expired-registration-cleaner-cfn.yaml
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/registration-cleaning-worker-cfn.yaml
notificationworkerlambda/riff-raff.yaml
notificationworkerlambda/sender-worker-cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/topic-counter-cfn.yaml

Currently our notification Lambdas are skirting very close to the limit of 250MB available for an S3 based Lambda (in fact strictly speaking we are over the limit at somewhere around 300MB but there must be some buffer). As a result, a change in our dependencies risks pushing us over the edge and making it so we can no longer deploy our Lambdas.
An alternative would be to use container images for our Lambdas instead:
> When you create a Lambda function, you use a deployment package to deploy your function code. Lambda supports two types of deployment packages: .zip file archives and container images.
>
> You can use the Lambda console and the Lambda API to create a function defined as a container image, update and test the image code, and configure other function settings.
(from …

Convert our Notification Lambdas to use Container Images

---

notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/sender-worker-cfn.yaml

As discussed on the call, this PR updates the alarms to use the new lambda names. In fact, I have updated them to use `!Ref`s to the actual lambda so they shouldn't be dependent on the name any more.
This is currently deploy on `CODE` and all seems well:

alarms need to be updated for new lambda names

---

eventconsumer/cfn.yaml

The athena lambda cannot currently log to cloudwatch because stack has been added as a prefix to the function name but the corresponding policy not updated.
This PR also removes 2 resources that are no longer needed because the corresponding lambdas have been deleted.

Fix eventconsumer athena logging

---

build.sbt

Update log4j dependency to fix security vulnerability - see [doc](https://docs.google.com/document/d/1nVKsXiEXLviHOMY1iQEoyacvN93_SYCQwsOFfaP-dxo)
Ran tests locally

update log4j dependency to fix security vulnerability

---

.gitignore
api-models/version.sbt
build.sbt
project/build.properties
project/plugins.sbt
version.sbt

Updates the sbt version to 1.5.6 to fix a security vulnerability introduced through log4j
run sbt and test locally

Update sbt version to 1.5.6 to fix security vulnerability

---

build.sbt

The `mobile-logstash-encoder` library has been released with a few enhancements / bug fixes. Updating n10n to use that upgraded library.
Deploy branch in CODE; log lines should continue to include EC2 instance ID.

Upgrade mobile-logstash-encoder version

---

notificationworkerlambda/cdk/lib/senderworker.ts
notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala

PR #580 introduced a CDK version of the n10n sender lambdas, but in order to deploy it with an easy backout route, it was merged and deployed but not activated (i.e. Harvester is still using the old SQS queues which exist in parallel).
Everything looks like it went smoothly (and there have been numerous notifications sent out since it was deployed), so I think we are good to do the switchover now. 
As such, this change will activate the new CDK stack, after which time, once everything is confirmed to be working, we can tear down the old stack. This change is currently deployed on CODE and I have tested that it works and that it causes the notifications to switch over to the new stack.

Wire up the CDK that was introduced in PR #580

---

notificationworkerlambda/registration-cleaning-worker-cfn.yaml
notificationworkerlambda/riff-raff.yaml

When updating the `riffraff.yaml` for PR #580 , we accidentally removed one of the lambdas from the riffraff file which was still being used.
The effect of this is only that it has not been being redeployed, it wasn't actually deleted from AWS.
But we do need to reinsert this missing line in case we want to update its code later on.
I am also updating the description as it doesn't seem to match what this lambda does.

replace the accidentally removed cleaning worker

---

build.sbt
project/plugins.sbt

The first thing we do when creating the Docker image which is use for the notification lambdas, is to include set the parent image to be the latest instance of the [AWS Java Lambda runtime](https://gallery.ecr.aws/lambda/java):
```scala
// build.sbt
lazy val lambdaDockerCommands = dockerCommands := Seq(
Cmd    ( "FROM",   "public.ecr.aws/lambda/java:latest"),
```
This works fine, but there is no way to identify afterwards, by looking at the image, which version of the AWS lambda runtime image it was built from. This means that if a new version of the upstream image is released after this image was built, there is no way to show that this image was built on an old version and therefore needs to be updated.
What this change does is add a Docker `LABEL` to the freshly built image, which …

Include a label within the container image which identifies which base image was used

---

.github/dependabot.yml

Adds dependabot for our npm and github actions, for CDK directory

Add dependabot for npm and github actions

---

notificationworkerlambda/registration-cleaning-worker-cfn.yaml

The function name for the registration cleaning worker lambda sqs queue didn't include the updated "ctr" version, and so the link was broken between the lambda and the queue. This was only noticed when riff-raff made a change and triggered a build which updated the sqsmapping and the cloudformation failed to update. 
The cloudformation succeeds in a build
The queue has 1600 messages on it that haven't been processed, hopefully the batch size of 1 means we just process one message at a time and it doesn't overwhelm the database

Update the function name for the registration cleaning worker lambda

---

.github/workflows/cdk-test.yml
project/plugins.sbt

The snyk execution in the teamcity build failed because it does not support the new addDependencyTreePlugin annotation in `plugins.sbt`.  This PR is to change the way we added the dependency tree plugin to the project as instructed by Snyk.
We started the build `mobile-notifications-snyk` in teamcity and it was successful.

Snyk does not support the new addDependencyTreePlugin annotation

---

build.sbt

Bumping the jackson dependencies to resolve high severity security alerts from snyk.
In MAPI we found that we had errors if not all jackson dependencies were on the same version, hence why we're bumping all 3 jackson dependencies here in one go.

Resolve snyk issues by bumping jackson modules to latest version

---

build.sbt
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
project/plugins.sbt

To fix security vulnerabilities introduced in the notification worker lambda we:
- Updated firebase admin version to the latest (8.1.0)
- Relied on google oauth client as a direct dependency to fix the transitive security vulnerability
Deploy to CODE and send a test notification, making sure it works

Update firebase admin, make google oauth a direct dependency

---

.github/workflows/cdk-test.yml
api-models/README.markdown

We are renaming the default branch from `master` to `main`.
This PR updates the github action `cdk-test` workflow yaml and readme files on the name of default branch.

Renamed default branch from master to main

---

project/plugins.sbt

This PR bumps the play framework to version 2.8.16.  It fixes the vulnerability "com.typesafe.akka:akka-http-core_2.13
Improper Resource Shutdown or Release" found in snyk scan.
All unit tests were passed.  Local snyk scan confirmed the vulnerability concerned was fixed.

Bump play framework to 2.8.16

---

build.sbt

We saw that we could not deploy a number of mobile-n10n modules (e.g. notification API, registration) in riff-raff.  Further investigation showed that some configurations were missing in the sbt:
This PR adds the required settings to sbt so that the riffRaffUpload could work for all modules.
All mobile-n10n modules could be shown in riffraff deployment page after teamcity build.  We succeeded to deploy `notification` via riff-raff.
Yes, no risks were found as it changes the riffraff upload settings only.

Add riffRaff upload settings to sbt

---

build.sbt
project/plugins.sbt

In this [PR](https://github.com/guardian/mobile-n10n/pull/660#discussion_r906032803) it was suggested to bump sbt-riffraff-artifact to the latest version and then remove redundant configuration. This change implements the recommendations.
We can see in the corresponding build that team city has published [artifacts](https://teamcity.gutools.co.uk/buildConfiguration/Mobile_MobileNotificationsAll/782984?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandCode+inspection=true&showLog=782984_7618_5362&logView=flowAware) to the expected bucket and the associated build can be deployed via riffraff.
Push commit
Validate team city publishes artifacts correctly
Validate build can be deployed via riffraff

Bump sbt riffraff artifact

---

common/src/main/scala/models/NotificationLogging.scala
notification/app/notification/controllers/Main.scala

This change adds some custom logging into the notification app (the harvester and workers apps will have additional logging in subsequent PRs). The aim is to increase observability of the performance of the notification send flow and forms part of a task to implement a test rig in CODE that enables us to understand/measure changes to our system.
Some rationale for the abstraction of the custom logging fields:
- I moved it into common because multiple apps will probably want to log with custom fields
- The custom log fields rely on a change to the index pattern in our elk stack. The additional fields that have been manually added include a specified type, which now matches the types for the `value` in the case classes.
The custom logs will power a …

LIVE-4203: log system metrics for the notifications app

---

notification/app/notification/services/guardian/GuardianNotificationSender.scala
notification/test/notification/services/guardian/GuardianNotificationSenderSpec.scala

Reverts guardian/mobile-n10n#659
Looking at the stats for our 90% in 2mins target, it appears that this change hasn't improved the situation:
We agreed to revert and continue to monitor.

Revert "LIVE-4234 increase shard size"

---

docs/testing/00-notification-improvement-plan.md
docs/testing/04-reducing-lambda-duration.md

No code changes, only documenting the results of defining provisioned concurrency for the harvester lambdas.

Document testing of provisioned concurrency

---

docs/testing/00-notification-improvement-plan.md
docs/testing/06-reducing-lambda-cold-start-times.md

Document the testing we've done to try and reduce the lambda cold start time (no code changes)

Document testing to reduce lambda cold start time

---

docs/testing/00-notification-improvement-plan.md
docs/testing/07-lambda-timing.md

No code changes just documenting some research we did around how close we are to meeting our SLO for breaking news notifications.
High level summary: we need to reduce our current total duration by about 60% for breaking news notifications to meet the SLO. Our current bottleneck looks to be how the sender lambdas scale.

How lambda timings correlate to meeting our SLO

---

dynamo.yaml

For the apps metering project we need an event stream from the notifications table. We can use this to exclude articles from metering.
Because the notifications service writes to the dynamo table before initiating the send, we should get these events ahead of the mobile apps.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-streamspecification.html

Add stream to notifications-reports dynamo table

---

build.sbt

The PR bumps the Postgresql client library to version 42.4.1 to fix the snyk vulnerability of sql injection.
All unit tests pass.

Bump the Postgresql library to 42.4.1

---

docs/architecture/03-postgresql-upgrade.md
docs/architecture/03-postresql-upgrade-procedure.md
docs/testing/05-database-tuning.md
docs/testing/06-postgresql-upgrade.md

We are planning to perform database engine upgrade on the registrations database from Postgresql 10.18 to a newer version.
The documents in the PR summaries the study on the database upgrade, the recommendation, the detailed procedures and the test result.

LIVE-3899 postgresql upgrade

---

notification/app/notification/controllers/Main.scala
notification/test/notification/controllers/MainSpec.scala

The reliability team has provided a very useful [doc](https://docs.google.com/document/d/10AnOZ4MLjuTO7mXaySoVO2SwmroLmns4gGmsfY7egmw/edit?usp=sharing) about how to incorporate metrics into our notification platform. 
This PR adds metrics to the notification app only:
- notification app processing time
- count of breaking news notifications
This PR also changes the logic for how duration is calculated: previously the duration didn't account for the Future completing so the duration looked to always be ~0ms. Now I'm seeing more realistic durations (600-1700ms).
I can see that the metrics are being pushed to cloudwatch as expected:
I pushed to CODE, sent a couple of test notifications and checked:
- logs
- kibana dashboard
- cloudwatch metrics
Given we publish these metrics I think we'll …

Notification app metrics

---

docs/testing/08-thread-pool-size.md

No code changes, just documenting the results and recommendations from the testing around increasing the thread pool size.
Branch for reference: https://github.com/guardian/mobile-n10n/tree/sender-lambda-custom-execution-context

Document test results from increasing thread pool size

---

build.sbt

This PR bumps the dependency on firebase admin to the latest version, we have recently been seeing some errors in our logs such as:
```sending failure: com.gu.notifications.worker.delivery.DeliveryException$FailedRequest: Request failed (Notification: 9694efd8-766e-36fe-b952-c4c15ed55bf4, Token: fi8bOpe4hpE:APA91bEwB0wxtYzSYwoM4DsEqfTDY8usq5zgEBbUHtN-FQtmFdgyUy7X1vzpF9ybZ9viM6_xFgchBVKIRzRqz6EHZ2TJ9sS8fzYX419sRM84GnZ6el61vZtawfNXH5-VIYurfbF2Fa2d). Cause: Internal error encountered.. ErrorCode: Some(INTERNAL)}```
and 
```Sending failure: com.gu.notifications.worker.delivery.DeliveryException$FailedRequest: Request failed (Notification: 1f8efa25-61e9-4da8-974e-7022dc6a6011, Token: fXVZX70wQPSsLnKVchApuX:APA91bHebes1c-aXXvAAwji-Gj3MWUuL62zrgdb6GjbWFEEfH0pbkhK2HGJXisXN-KZ4jerYucUEp-17NudTTdWQr …
```

Bump firebase admin version to the latest

---

notificationworkerlambda/registration-cleaning-worker-cfn.yaml

We would like to deploy https://github.com/guardian/mobile-n10n/pull/739 which will temporarily put increased load on the db due to a large volume of invalid tokens that we expect to parse.
Previously when we processed a large number of messages from the cleaning queue it resulted in poor performance when delivering notifications: https://docs.google.com/document/d/1svFwqn2MBVue-gSQvkS5u2MAQsOO8aOyPJeMcj26i88/edit?usp=sharing
We would like to temporarily slow down the cleaner lambda by reducing the number of parallel executions. The intention is that this would control any additional load on the db, preventing delivery of notifications to be noticeably slowed down.
This reduces the cleaning lambda's reserved concurrency to 1. As a result, we may expect to see throttle alerts for this …

reduce reserved concurrency for registration cleaning worker

---

slomonitor/src/main/scala/com.gu.notifications.slos/SloMonitor.scala
slomonitor/src/test/scala/com/gu/notifications/slos/SloMonitorSpec.scala

We pushed the slomonitor lambda into production to collect data about the accuracy of the 90in2 count. The results revealed an edge case that severely impacted data accuracy for a specific scenario:
- A notification was sent at 23.59
- The athena query only counted results from the same day
- The majority of the notifications were received within the 2nd minute after sending, i.e. 00.01 the following day, and so were accidentally excluded from the 90in2 count
This PR attempts to handle the edge case to improve the data accuracy of slomonitor's 90in2 count:
- extract and extend the logic that generates the athena query string
- create test cases for query string generation
- refactor slomonitor object to extend from a trait allowing env vars to be overridden in tests
We've added unit tests …

Include multiple partition_dates if notification sent just before midnight

---

notificationworkerlambda/registration-cleaning-worker-cfn.yaml

Reverts guardian/mobile-n10n#745
Now that we’ve successfully deployed #739  we can revert the concurrency restriction we put on the cleaning worker #745

Revert "reduce reserved concurrency for registration cleaning worker"

---

build.sbt
slomonitor/src/main/scala/com.gu.notifications.slos/SloMonitor.scala
slomonitor/src/test/scala/com/gu/notifications/slos/SloMonitorSpec.scala

slomonitor was failing to execute in aws because of missing class constructor, we believe it's caused by recent refactoring of trait/object in #771. Refactoring the tests and trait/object to fix this error.
Deployed to CODE, sent a breaking news notification, validated slomonitor executed correctly.

Fix failing slomonitor

---

docs/architecture/05-cache-tokens.md

This PR adds a document which summarises the feasibility study of caching all the device tokens in the memory of Notification APIs.
No changes have been made to the source code.

Live 4580 document cache tokens

---

notification/conf/riff-raff.yaml
registration/conf/riff-raff.yaml
report/conf/riff-raff.yaml

DevX informed us that their [recommendations](https://github.com/guardian/recommendations/blob/main/github.md#repository-contents) for repository content suggests not committing S3 bucket names into public repositories. Previously the riff-raff.yaml file requires a bucket name for the autoscaling deployment type.  They are now able to provide bucketSsmLookup: true and have Riff-Raff discover the S3 bucket to copy the application artifact to via an SSM parameter.
This PR is to change the riff-raff yaml in Notification settings so that it resolves the bucket name by SSM parameter.
A SSM parameter has been created for the bucket name used by n10n. 
We tested that registration request has been handled successfully.  A fake notification was sent successfully as well.

Resolve bucket name by SSM parameters

---

eventconsumer/riff-raff.yaml
football/riff-raff.yaml
reportextractor/riff-raff.yaml
schedulelambda/riff-raff.yaml

DevX informed us that their [recommendations](https://github.com/guardian/recommendations/blob/main/github.md#repository-contents) for repository content suggests not committing S3 bucket names into public repositories. Previously the riff-raff.yaml file requires a bucket name for the autoscaling deployment type. They are now able to provide bucketSsmLookup: true and have Riff-Raff discover the S3 bucket to copy the application artifact to via an SSM parameter.
The previous PR #788 changed the riff-raff yaml for the web services (notification, registration, report).
This PR changed the riff-raff yaml for the lambdas. 
We checked that the riff-raff deployment resolved the bucket to the correct one on `CODE` and copied the function packages to the bucket.
We also checked that the function …

LIVE-4673 Use bucket name lookup in riff-raff yaml

---

.gitignore
README.md
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/NotificationWorkerLocalRun.scala

We want to test and validate new methods for sending notifications/tokens via firebase. Having a local setup for sending notifications will enable us to quickly test new functions without needing to deploy to CODE.
This change adds the ability to execute the ios and android worker lambdas locally.
- create an object that allows us to run the lambda handler functions locally
- update readme with setup instructions for running the worker lambdas locally
- export Platform env var
- create notification-worker.conf file with CODE values
- start sbt and change to project notificationworkerlambda
- `run NotificationWorkerLocalRun android`
- see valid response from firebase

Run worker lambdas locally

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmClientTest.scala

In #729 we increased the thread pool size as a way of increasing performance in the notification system. This probably wouldn't have been necessary if we did not have blocking code.
As discussed [here](https://github.com/guardian/mobile-n10n/pull/729#issuecomment-1284068735) the blocking code has been identified and a solution discussed.
In this PR we've refactored sendNotification() and extracted parseSendResponse() so that we can test the response parsing more easily (without having to mock all the Future-related interactions).
We have validated that the unit tests still correctly parse the response from firebase.
We ran the lambda locally and could see the future completing.
We should monitor the n10n [dashboard](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1# …

Removing blocking code from the firebase client

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/sender-stack.test.ts.snap
cdk/lib/sender-stack.test.ts
cdk/lib/sender-stack.ts

We are building a EC2-based sender worker to further improve the performance of the notification delivery pipeline.
This PR creates the stack using GuCDK.  The stack mainly defines:
1. an autoscaling group to host the new sender worker process, and
2. five SQS queues for harvester to send messages to the new sender worker 
Based on current mechanism where harvester gets the URLs of the sender queues, it creates five parameters in SSM for the new queues:
- `/notifications/CODE/workers/harvester/androidBetaSqsEc2Url`
- `/notifications/CODE/workers/harvester/androidEditionSqsEc2Url`
- `/notifications/CODE/workers/harvester/androidLiveSqsEc2Url`
- `/notifications/CODE/workers/harvester/iosEditionSqsEc2Url`
- `/notifications/CODE/workers/harvester/iosLiveSqsEc2Url`
It also exports the ARNs of …

LIVE-4702 create AWS stack for EC2-based sender worker

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/NotificationWorkerLocalRun.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala

We currently use metrics to see the performance of the whole system. For worker lambdas we have a metric for the processing time, which includes the length of time a message sits on a queue. This is great for determining the impact of changes to the overall performance.
In future PRs we are going to test using batch api calls. This PR adds a new metric to enable us to evaluate improvements to the lambda function.
The `functionProcessingRate` is a metric for how quickly we process tokens. The rate is calculated by:
`number of tokens processed by a particular function invocation / function processing time in seconds`
The result is that we get a metric representing the number of tokens being processed per second.
To capture this metric there were a number of changes required:
- Refactor the …

Create metric for worker lambda processing rate

---

build.sbt
cdk/lib/__snapshots__/sender-stack.test.ts.snap
cdk/lib/sender-stack.ts
senderworker/riff-raff.yaml
senderworker/src/main/scala/SenderWorker.scala

We are building a EC2-based sender worker to further improve the performance of the notification delivery pipeline.
The previous PR #793 created a new cloudformation stack for the sender worker we are looking to build.
This PR set up a sub-project in the repo with the corresponding riff-raff configuration for deployment.
Specifically, it contains the following changes:
1. Create a new subproject `senderworker` which is a Scala project
2. It depends on `notificationworkerlambda`.  The JAR is included in the output package of `senderworker`
3. It is packaged as Debian package and deployed as a Systemd service (just like MAPI microservice)
4. At this moment, the Scala program does nothing (except printing some messages to confirm it is executed)
5. `AWS-kinesis-agent` is set up to copy logs …

LIVE-4705 set up deployment for EC2-based sender

---

cdk/lib/__snapshots__/sender-stack.test.ts.snap
cdk/lib/sender-stack.ts

Adds a new parameter to store the EC2 Workers SQS Queues URLs. This is so we can use the parameter to retrieve messages from the SQS queues. We know the parameter already exists for the harvester, the neatest way is to duplicate that parameter and modify the name for the ec2 worker namespace.
Deploy to CODE and see if the parameter is generated

LIVE-4704: Add ec2 worker sender queue url parameter

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
senderworker/src/main/scala/com/gu/notifications/ec2worker/Configuration.scala

Adds ec2 url parameter to apns and firebase config, this will be used later for polling a queue to receive messages.
Deploy to CODE and check it loads configuration correctly

LIVE-4704: Add ec2 url parameter to apns and firebase config

---

notificationworkerlambda/harvester-cfn.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala

We are building a EC2-based sender worker to further improve the performance of the notification delivery pipeline.
In option 1, we plan to have both the lambda sender worker and EC2-based sender worker running in parallel during the migration and testing phase, and we route the notification tokens based on the topics of the notification.
This PR implements this stack switching feature in the harvester worker.
It makes the following changes
1. Read the new parameters about the URLs of the new SQSs from SSM
2. Read the new parameter `allowedTopicsForEc2Sender`
3. Instantiate two sets of `SqsDeliveryService`, for the old SQSs and for the new ones.
4. Dispatch the tokens to the set of `SqsDeliveryService` based on the topic.  If all topics of the notification are on the list, it goes to the …

LIVE-4701 create stack switch in harvester

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/cleaning/CleaningClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliverySuccess.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/SendingResults.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Reporting.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmClientTest.scala

In https://github.com/guardian/mobile-n10n/pull/747 we enabled multicast messaging for specific topics. The multicast message endpoint allows us to send up to 500 tokens in a single http request (as opposed to a single token per http request in our pre-existing implementation). The intention was to test whether batching tokens would increase the rate at which lambdas could process tokens.
Batch sending has been limited to topics `breaking/international` and `breaking/international-sport`. Since deploying the previous change some notifications have been sent using the multicast message endpoint. The general results show:
- the 90in2 metric has not changed (but we don't expect it to because ios is excluded from this test).
- the number of android users receiving notifications for these two …

Update parsing logic for multicast message response

---

cdk/lib/__snapshots__/sender-stack.test.ts.snap
cdk/lib/sender-stack.ts
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
senderworker/src/main/scala/com/gu/notifications/ec2worker/Configuration.scala

Adds ec2 url parameter to apns and firebase config, this will be used later for polling a queue to receive messages. Also adds an sqs url parameter to the old worker config.
Deploy to CODE and check it loads configuration correctly, check the lambda still works as expected.

LIVE-4704: Add sqs url parameters to apns and firebase config

---

notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/lib/senderworker.ts
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/SendingResults.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/NotificationParser.scala

This PR is intended to test the performance improvement of multicast message sending by enabling more multicast message http requests to take place concurrently. The theory is that we have the ability to parallelise within our lambda, but it is currently under-used when sending groups of tokens to firebase.
We want to increase the function processing rate of our worker lambdas because they are the bottleneck for achieving our 90in2 SLO. We recently tried [testing](https://github.com/guardian/mobile-n10n/pull/747) the impact of multicast message sending our tokens to firebase. We observed the following results:
- the latency of a multicast message request was higher than the latency of a request to send an individual token (2600ms vs 70ms, respectively)
- the latency for sending 500 tokens …

Process multiple sqs event records concurrently

---

notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/lib/senderworker.ts

We are testing the performance impact when concurrently handling multiple sqs messages inside a single sqs event.
Yesterday we found that performance degraded when handling 20 sqs messages and sending individual notifications (not in groups).
This change scopes the sqs batch size configuration android only, only the android worker will have:
- an sqs batch size of 20, all other workers revert to a batch size of 1
- a max batching window of 1 second
- a timeout of 180 seconds, all other workers revert to the original timeout of 90 seconds
- a visibility timeout of 200 seconds, all other workers revert to the original visibility timeout of 100 seconds
After deploy, confirm the lambda configuration has been updated correctly for the non-android workers.

Apply sqs batch size changes to android worker only

---

notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/lib/senderworker.ts

We deployed a [change](https://github.com/guardian/mobile-n10n/pull/823) that enabled the android worker lambda to concurrently process batches of SQS messages.
Since that deploy we have observed the following:
- increased number of errors received
- new error types being returned to us, including api client timeout errors
- android lambdas failing to process entire batches of tokens, and then having to retry
Given the SQS batching is the most recent change, this PR reduces the SQS batch size to try and reduce the errors that we're receiving.
Given the change is deployed, confirm that the android worker lambda has an SQS batch size of 10.
Reduction is errors received when sending breaking news notifications.

Reduce SQS batch size for android worker

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala
senderworker/src/main/scala/com/gu/notifications/ec2worker/SenderWorker.scala

This PR is part of the work to create metrics and alarms to monitor EC2 stack after it is rolled out.
It enables the sender function to create AWS metrics under different namespaces so that we will be able to differentiate between metrics from worker lambda and EC2 sender.
It also adds a _start_ log before processing a SQS message.  This log is needed to create the concurrency level graph as proposed in #825 (the 6th item). 
I deployed the worker lambda to CODE and verified that the AWS metrics were created under the correct namespace `Notifications/$stage/workers` and the `start` logs were created.  I also updated the sample Kibana dashboard ( https://logs.gutools.co.uk/s/mobile/app/dashboards#/view/75c0d220-6447-11ed-be34-2d379af36700?_g=(filters:!()) ) with the created logs.

LIVE-4729 Separate AWS metric namespaces for sender lambda and EC2 sender

---

build.sbt

Firebase recommended bumping `firebase-admin` to the [latest](https://firebase.google.com/support/release-notes/admin/java). This PR updates the version specified.
Although there appear to be no changes relevant to firebase messaging in the release notes it is probably good to migrate anyway.

Bump version of firebase-admin to latest

---

cdk/package-lock.json
cdk/package.json
notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/package.json
notificationworkerlambda/cdk/yarn.lock

We need to be on a very recent GuCDK version in order to use the new constructs for error budget alerting (https://github.com/guardian/cdk/pull/1576). Consequently, this PR upgrades GuCDK to the latest version. We also update the AWS cdk dependencies to match the versions that GuCDK needs.
The snapshot tests indicate that the `gu:cdk:version` tag is the only thing that's changing. I have also deployed the relevant projects to `CODE`[^1] to confirm that the deployments work and that no resources are deleted.
Everything should continue working as before, but we'll be able to make use of `GuErrorBudgetAlarmExperimental` in a future PR.
Yes, this should be pretty low risk as the only changes caused by this upgrade are related to tagging.
Although there is a major version bump here [the …

Upgrade cdk dependencies to the latest version

---

build.sbt
cdk/bin/cdk.ts
cdk/lib/__snapshots__/registration.test.ts.snap
cdk/lib/registration.test.ts
cdk/lib/registration.ts
registration/conf/registration.yaml
registration/conf/riff-raff.yaml

We would like to use the new constructs for error budget alerting (https://github.com/guardian/cdk/pull/1576) so that we receive warnings if we are at risk of missing SLO(s) for the Registration service.
This PR imports the Registration YAML via GuCDK in order to configure these alerts, as doing so will make it easier[^1] to reference the correct metrics in TypeScript code and also simplifies deploying the error budget alarm configuration via Riff-Raff. Finally, the work here is the [first step in migrating the Registration app to GuCDK](https://github.com/guardian/cdk/blob/main/docs/migration-guide.md#introduce-cdk-to-the-repository-with-cicd)[^2], so we will need to do it at some point anyway! 
cc @guardian/devx-reliability 
This shouldn't change any behaviour - I've [deployed to …

Set up GuCDK stack for Registration and deploy stage-specific templates

---

build.sbt

After bumping the firebase lib we lost some logs in notification sender worker lambdas, it referenced this page:
https://www.slf4j.org/codes.html#ignoredBindings
Which suggests we need to bump the logback-classic version.
We also bumped:
- slf4j-api version explicitly to be the version required 
- we didn't bump logback-classic to the latest because it looks incompatible with our java version
Ran notification worker local run and could see logs being printed successfully again to the console.

Bump logging libraries

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/sender-stack.test.ts.snap
cdk/lib/sender-stack.ts

We are building a EC2 implementation of sender worker, which is one of our experiments to further improve the performance of the notification delivery pipeline.
This PR creates alarms to help us monitor the health of the EC2 stack after it is released to PROD.  For each of the platforms (`android, ios`, `android-beta`, `android-edition`, `ios-edition`), it creates four alarms according to the [proposal](https://github.com/guardian/mobile-n10n/blob/main/docs/architecture/06-monitor-ec2-stack-rollout.md) in #825  
I examined similar metrics on the existing worker lambdas to figure out what reasonable values we should use for the thresholds initially:
The largest value for this metric was 650.  I set the threshold of the alarm to 700
The largest value for this metric was 350.  I set the …

LIVE-4729 create alarms for EC2 stack rollout

---

cdk/lib/__snapshots__/registration.test.ts.snap
cdk/lib/registration.ts

Fixes a problem with https://github.com/guardian/mobile-n10n/pull/855 which caused `PROD` deployments to fail.
Alarm names must be unique, so the fact that we have already deployed these alarms in `CODE` means that we cannot deploy them to `PROD` 🤦‍♂️ 
The SLO name that we pass into the construct is used to generate the alarm names in CloudWatch, so we can fix this problem by adding the stage to the SLO name. The GuCDK construct should probably do this automatically (and I might add that in the future), but that requires a library release so this PR is a faster fix!
I will deploy to `CODE` and then `PROD` and hope that it works this time!
We should be able to deploy to `PROD` again!
This should be pretty low risk; it will recreate all alarms but that should be perfectly safe.

Ensure that alarm names are unique across different stages

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/IOSSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/models/ApnsConfig.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/apns/models/payload/ApnsPayloadBuilderSpec.scala
senderworker/src/main/scala/com/gu/notifications/ec2worker/Configuration.scala

In this PR we make `maxConcurrency` and the number of concurrent connections configurable properties. This will enable testing and tuning of the ios sender worker as part of future experiments.
SSM variables will be created with the current values:
- maxConcurrency: 100
- number of concurrent connections: this wasn't previously specified, but the [default](https://github.com/jchambers/pushy/blob/master/pushy/src/main/java/com/eatthepath/pushy/apns/ApnsClientBuilder.java#L75) value is 1
Given this change is deployed, we should expect to see no changes. The current values of the new configurable properties have been set to what we already use:
- maxConcurrency: 100
- number of concurrent connections: 1
We should expect both the sender lambdas and the ec2 workers to start up correctly, …

LIVE-4823: Define new configurable properties for iOS sender worker

---

slomonitor/src/main/scala/com.gu.notifications.slos/SloMonitor.scala

Fixes a bug introduced by https://github.com/guardian/mobile-n10n/pull/866, which is caused by using `+` with `String`s instead of `Double`s 🤦‍♂️:
`Notifications delivered within 120 seconds was 374718449495` 🤯 
I have deployed to `CODE` and checked the logging: 
The logging should be truthful again after this PR is merged.
I think this is pretty low risk.

Fix logging for 90in2 deliveries

---

.gitignore
.tool-versions
eventconsumer/cfn.yaml
fakebreakingnewslambda/fakebreakingnewslambda-cfn.yaml
fakebreakingnewslambda/riff-raff.yaml
football/cfn.yaml
notification/conf/riff-raff.yaml
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
registration/conf/riff-raff.yaml
report/conf/riff-raff.yaml
reportextractor/cfn.yaml
schedulelambda/cfn.yaml
senderworker/riff-raff.yaml

We are exploring the new AWS `Snapstart` feature to reduce the cold start initialisation time of the sender lambda in our effort to increase the overall notification delivery performance.  The `Snapstart` feature requires Java11 runtime so we have to upgrade the lambda function from Java 8 to Java11.
Other important reasons are:
1.  it was reported that Graviton servers achieve better performance on Java 11 
2. more generally, newer Java versions support newer language and platform features
3. it is suggested that future Scala 3 versions may drop support for Java 8
4. the Play Framework, which is used in `registration`, `notification` and `report`, announced that the next major version (2.9) will drop support for Java 8
This PR upgrades the whole project to use Java11.
Major changes are: …

LIVE-4850 upgrade to Java 11

---

common/src/main/scala/models/ShardedNotification.scala
notification/app/notification/controllers/Main.scala
notification/app/notification/services/NotificationSender.scala
notification/app/notification/services/frontend/FrontendAlerts.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notification/test/notification/controllers/MainSpec.scala
notification/test/notification/services/frontend/FrontendAlertsSpec.scala
notification/test/notification/services/guardian/GuardianNotificationSenderSpec.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/NotificationWorkerLocalRun.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliverySuccess.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/SendingResults.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Reporting.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmClientTest.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/models/SendingResultsSpec.scala

cc @michaelwmcnamara (who also worked on this PR)
This PR allows us to calculate (and collect CloudWatch metrics for) token delivery latency.
This means that we can use a standard latency metric in CloudWatch to visualise internal stack performance (i.e. we can check how the stack is performing in isolation of Firebase/APNS delivery times, which may be unpredictable). For example, we can calculate the 99th, 95th & 90th percentiles for token delivery latency. 
We can also calculate an SLI based on this metric, for example:
Good events = _the number of token deliveries where the delivery took less than X seconds_
Valid events = _the number of token deliveries_
SLI = _(the number of token deliveries where the delivery took less than X seconds / the number of token deliveries) * 100_ 
IIUC a …

Collect token delivery latency metrics

---

build.sbt

This PR bumps the protobuf-java dependency to fix the high severity of snyk vulnerabilities.
All unit tests have passed in the teamcity build.

Bump protobuf-java

---

build.sbt

Bumps the version of protobuf-java to 3.20.3.

Update to protobuf-java 3.20.3

---

common/src/main/scala/models/NotificationMetadata.scala
common/src/main/scala/models/ShardedNotification.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Harvester.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/NotificationWorkerLocalRun.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/SendingResults.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Cloudwatch.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala

cc @michaelwmcnamara (who also worked on this PR)
This change is a follow-up to https://github.com/guardian/mobile-n10n/pull/884. It modifies the CloudWatch metrics sent from the notifications worker lambdas to include a dimension tracking the audience size for each notification. This replaces the `type` dimension (which captured whether the notification was `breakingNews` or `other`) in order to prevent us from creating too many unique metrics[^1].
The reason for this switch to audience size is:
1. IIUC there is no significant functional difference between the handling of Breaking News and other notifications.
2. The size of the audience for Breaking News notifications varies wildly between 10,000 and more than 1,000,000 (see the [Ophan notifications …

Categorise notifications based on their audience size to support SLI bucketing

---

common/src/main/scala/models/ShardedNotification.scala
notification/app/notification/services/guardian/GuardianNotificationSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/NotificationWorkerLocalRun.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/HarvesterRequestHandlerSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/SenderRequestHandlerSpec.scala

Now that https://github.com/guardian/mobile-n10n/pull/943 has been merged for a while, we can be sure that all messages in our SQS queues will have the `metadata` field with `NotificationMetadata`. This means that we can simplify the models by making this property mandatory.
I have deployed this to `CODE` and confirmed that a dry-run notification can still be processed.
We can simplify the models and remove a couple of fallbacks which don't really make sense.
Merging this makes it slightly harder to rollback https://github.com/guardian/mobile-n10n/pull/943, but that change has been out for ~24 hours and it seems to be working fine, so I think that's OK.

Make NotificationMetadata mandatory in models

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/models/SendingResults.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/models/SendingResultsSpec.scala

In https://github.com/guardian/mobile-n10n/pull/943, we configured audience bucket sizes (for tracking purposes). We [based the initial sizing on the delivery data in Ophan](https://github.com/guardian/mobile-n10n/pull/943#discussion_r1095756893), but this seems to differ significantly from the audience sizes for each topic in the DB.[^1] 
Consequently this PR modifies the bucket sizes so that we treat different audiences as intended (for example, we need to increase the lower limit for the XL audience size to ensure that this only matches global breaking news notifications).
I have deployed this to `CODE` and confirmed that a dry-run notification can still be processed. I've also added a unit test.
The bucket sizes should now line up with our original intentions, as explained …

Modify bucket sizes based on full topic counts

---

notification/conf/riff-raff.yaml
registration/conf/riff-raff.yaml
report/conf/riff-raff.yaml
senderworker/riff-raff.yaml

Ubuntu bionic (v18) will reach end of support by April 2023.  The PR changes the EC2-based services (`registration`, `notification`, `report` and `ec2sender`) to use the new AMI which is based on Ubuntu Jammy (v22).
The services were deployed to `CODE` successfully.  
The following tests were performed to validate the new AMI:
1. a notification was sent successfully and my debug app was able to receive it
2. registration requests were handled properly.  Changes were verified in the database
3. we retrieved the report on the test notification from the `report` endpoint successfully
4. no tests were done on `ec2sender` as we are not using it and it will be removed soon
No error logs were found during testing.

LIVE-5049 Change to AMI using ubuntu Jammy

---

notification/conf/riff-raff.yaml
registration/conf/riff-raff.yaml
report/conf/riff-raff.yaml

It's good practice to use encrypted AMIs and this PR updates the riff raff configuration to consume encrypted ones. The n10n repo defines 3 EC2 services that will consume the encrypted recipe: `notification`, `registration` and `report`.
In amigo I cloned the existing recipe and then edited it to request an encrypted copy for the mobile aws account:
I manually triggered a bake and could see that an encrypted copy had been created as part of the process:
We can then find the corresponding encrypted AMI in the mobile account:
I updated the riff-raff configuration for the 3 EC2 services in this repo and deployed to CODE:
`notification`: I sent a test notification, the service returns an expected 201 response and I subsequently received the notification.
`registration`: I sent a POST request …

Use encrypted AMI

---

api-models/README.markdown
api-models/version.sbt

The mobile-notifications-api-model has changed, and the version was bumped in Maven:
Now we need to update the version.sbt file to the next version, which is 1.0.17.
**If**: The model has changed and the latest version has been released in Maven
**Then**: This version in version.sbt has to be updated to the next available version
**But**: The main branch is protected and we cannot push directly from main, so we need to do this through a separate branch

Set mobile-notifications-api-models version to 1.0.17

---

.github/workflows/dependency-updates-batch-updates-PR.yml

Now we're in BST the dependency updates PR is being raised after the mobbing session. This PR updates the cron schedule so that the action happens earlier in the day.
Dependency updates PR should happen at 11.45 UTC (12.45 BST)

Update time that dependency updates PR is created

---

cdk/bin/cdk.ts

Remove unused imports to suppress github warnings

Remove unused imports to suppress github warnings

---

.github/CODEOWNERS

Just so we get appropriate notifications and alerts.

Add mss-admins as codeowners

---

notification/conf/notification.yaml

A couple of our HTTP error alarms often go off and then immediately OK themselves, causing noise in our channel. By increasing the evaluation period we should be able to reduce this noise.
It appears they sometimes alarm because an instance becomes unhealthy, results in a connection error and then needs to boot up a new instance. Increasing the evaluation period should give it time to boot up a new instance. If it can't, we should then see this alarm after 10 minutes of there being an unhealthy instance.  
Note below how the times correlate between us seeing errors and there being an unhealthy instance.

Increase evaluation period for http code alarms

---

.scala-steward.conf
build.sbt
common/src/main/scala/utils/CustomApplicationLoader.scala
fakebreakingnewslambda/src/main/scala/fakebreakingnews/FakeBreakingNewsLambda.scala
football/src/main/scala/com/gu/mobile/notifications/football/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
reportextractor/src/main/scala/com/gu/notifications/extractor/Lambda.scala
schedulelambda/src/main/scala/com/gu/notificationschedule/ProcessNotificationScheduleLambda.scala
schedulelambda/src/main/scala/com/gu/notificationschedule/external/SsmConfig.scala

This PR bumps the [simple-configuration](https://github.com/guardian/simple-configuration) library to a newer version 1.5.7 from version 1.5.6
There are API breaking changes in `simple-configuration` between version 1.5.6 and version 1.5.7.  Please refer to guardian/mobile-apps-api#2797 for details.
This PR makes the following code changes for this new version of `simple-configuration`:
1.   In order to detect whether the service is running locally, I added a check on the environment variable "MOBILE_LOCAL_DEV" - if this environment variable is present, it assumes DevIdentity and bypassed the AppIdentity.whoAmI call (bypassing `AppIdentity.whoAmI` in local deployment was recommended in https://github.com/guardian/simple-configuration/pull/28). Otherwise it invoked AppIdentity.whoAmI and …

LIVE-5319 Bump simple-configuration to 1.5.7

---

dynamo.yaml
football/cfn.yaml

This PR allows us to start backing up the `mobile-notifications-reports-<stage>` and `mobile-notifications-football-notifications-<stage>` DynamoDB tables using https://github.com/guardian/aws-backup.
For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit) and this [audit](https://docs.google.com/spreadsheets/d/1gNh_yQ3GVo_dVAemgZfRZM_MaQxep6_x-hzrhvVBGHY/edit#gid=1523470588) that @guardian/devx-reliability have been working on with Heads of Engineering & EMs.
* `mobile-notifications-football-notifications-<stage>` is [deployed via Riff-Raff](https://github.com/guardian/mobile-n10n/blob/6edbd98c5426a5a8c53bdd51bd85c6dba6f8736c/football/riff-raff.yaml#L12-L18), so I have tested this by [deploying to …

Enable nightly backups for notification DynamoDB tables

---

build.sbt
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala

Google is going to discontinue some of its legacy Firebase Cloud Messaging (FCM) APIs and some of them are being used by our notification service.
We do not invoke the APIs directly.  These APIs are REST APIs where clients have to make HTTP requests directly to the FCM server endpoints.  Instead, we interact with FCM servers [via the Firebase Admin SDK](https://firebase.google.com/docs/cloud-messaging/server),  which provides a programming interface over the REST API.
To migrate from the old APIs being discontinued, we need to upgrade the Firebase Admin SDK to version 9.2.0, and replace our deprecated API call with the new APIs.  ([Firebase Admin Java SDK Release Notes](https://firebase.google.com/support/release-notes/admin/java) ).  Specifically we may have to replace our …

LIVE-6160 Upgrade firebase to v9.2.0

---

build.sbt
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/tokens/TokenService.scala

Reverts guardian/mobile-n10n#1206
We saw the following exception on Android sender:
```
com.gu.notifications.worker.delivery.DeliveryException$BatchCallFailedRequest: Entire batch request failed (Notification: 55b49b62-f93c-3ed9-abbc-4b3726f669c7, Multicast Async Response Failure: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached)
```
We need to study how we should configure

Revert "LIVE-6160 Upgrade firebase to v9.2.0"

---

notification/conf/notification.yaml

Editorials reported that they sent a breaking news notification via ed tools but no notifications were received.  The notification record was not found on Ophan dashboard either.
After investigation, it was found that the breaking news tool sent a HTTP request to our notification endpoint but received a 503 exception.  
The cloudwatch metric (ELB 5xx) for the load balancer of the notification API suggested that a 5xx response had been served from the load balancer at that time.  One of the EC2 instances was also terminated due to health check failure around that minute.
We noticed that EC2 instances of notification service failed health check from time to time.  The application logs of an unhealthy instance did not show any exception or error message, but the syslog of the OS indicated …

Use bigger EC2 instance for notification

---

.github/workflows/event-consumer.yml
.github/workflows/fake-breaking-news.yml
.github/workflows/football.yml
.github/workflows/notification-worker-lambdas.yml
.github/workflows/notification.yml
.github/workflows/registration.yml
.github/workflows/report-extractor.yml
.github/workflows/report.yml
.github/workflows/schedule-lambda.yml
.github/workflows/slo-monitor.yml

It was reported that the tests in the common projects such as `common` and `api-models` were not executed as part of CI.
This PR changes the GHA workflows to run tests in the common projects on which the target project depends.
The Github action works successfully as expected.
No changes to the source code or build configuration were made.

Run tests in common and api models as part of CI

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/DeliveryClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/apns/ApnsClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmTransportJdkImpl.scala

I paired with @aracho1 on this piece of work.
After merging PR #1216 , we saw IO exceptions when the android sender lambda sent notifications to a relatively larger group of device (more than several hundreds).
We used the same `HttpClient` instance for the processing of all SQS messages within an invocation of a lambda, and it appears that the `HttpClient` sent the requests over the same connection via HTTP/2.  In larger notifications, it hit the limit on the maximum of concurrent stream over a connection.
This PR attempts to fix the problem by creating a `HttpClient` instance for the processing of each SQS message.  Within each SQS message, there is a setting on concurrency level which specifies how many device token to send concurrently.  This approach helps us to control the maximum …

LIVE-6447 Create a connection for the processing of each SQS message

---

notificationworkerlambda/cdk/lib/senderworker.ts
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/SenderRequestHandler.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/utils/Logging.scala

The PR #1217 creates a `HttpClient` instance for the processing of each SQS client so that we don't send too many requests over the same connection.
However, the AWS lambda service reuses execution environment when it needs to invoke a lambda shortly after one has finished.  So it is possible that within the same Java runtime, the `AndroidSender` instance is used to process SQS messages many times and, as a result, creates too many `HttpClient` instances and the connections that are left idle.  The connections consume the limit on the file descriptors, which is [1024](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html#function-configuration-deployment-and-execution) for Java lambda runtime.  It is likely to happen when we send a huge notification (more than 100,000). …

LIVE-6468 Reuse http client across invocations

---

build.sbt
common/src/main/scala/metrics/MetricActor.scala
common/src/main/scala/metrics/Metrics.scala
notification/app/notification/NotificationApplicationLoader.scala
project/plugins.sbt
registration/app/registration/RegistrationApplicationLoader.scala
registration/app/registration/controllers/Main.scala
report/app/report/ReportApplicationLoader.scala

Minimal changes to upgrade to Play 3.0

Play 3.0 upgrade

---

.github/workflows/release.yml
api-models/version.sbt
build.sbt
project/plugins.sbt
version.sbt

This replaces the old release process which had developers manually running sbt release on their own laptops - each developer had to obtain their own PGP key and Sonatype credentials, which was an elaborate & fiddly process.
This PR adopts [gha-scala-library-release-workflow](https://github.com/guardian/gha-scala-library-release-workflow), which provides an automated release process that uses single shared set of release credentials, available through GitHub Organisation Secrets (like we already do with NPM) - this workflow allows you to [release a new library version](https://github.com/guardian/gha-scala-library-release-workflow/blob/main/docs/making-a-release.md) with the click of a button!
Most of the changes made here are documented in gha-scala-library-release-workflow's …

Adopt GHA Scala Library Release Workflow

---

build.sbt

Reverts guardian/mobile-n10n#1224 and re-enables the auto update on the release version

Re-enable release version auto-update

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/AndroidSender.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/Configuration.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmClient.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmTransportJdkImpl.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/FcmConfig.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/ConfigurationSpec.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmClientTest.scala

We notice that occasionally the Firebase API returns an internal error of service unavailable and then our Android sender lambda appears to stop working until it is terminated due to timeout:
It appears that the lambda may be waiting for responses from Firebase API who may have become _unavailable_.
At the moment, we do not set any timeout configuration for requests we send to Firebase API.  According to [API doc](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.net.http/java/net/http/HttpRequest.Builder.html#timeout(java.time.Duration)), the HTTP client waits indefinitely for responses by default.
This PR adds configurable parameters (`fcm.connectTimeout` and `fcm.requestTimeout`) to set the timeout (in seconds) of making HTTP connections and waiting for responses. …

Add timeout to HTTP requests to Firebase API in Android sender lambda

---

notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/FcmTransportJdkImpl.scala
notificationworkerlambda/src/main/scala/com/gu/notifications/worker/delivery/fcm/models/payload/FcmResponse.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmClientTest.scala
notificationworkerlambda/src/test/scala/com/gu/notifications/worker/delivery/fcm/FcmTransportJdkImplSpec.scala

We often receive alerts from android sender lambda about Firebase API returning 404 `Requested entity not found` errors.
From the [documentation](https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode), the error is raised when the device token we want to send a notification to is invalid, is unregistered, or has expired.  A device token becomes unregistered when, for example, the user uninstalls / reinstalls the app.  So it happens in normal situation.
This PR checks the `details` field of error messages from Firebase API and identifies invalid token errors.  The notification service already has a component to delete invalid tokens from the registration database.
We deployed to CODE and sent a test notification.  A notification was received successfully on my Android emulator. …

LIVE-6627 Fix the handling of unregistered token errors from Firebase API

---

.scala-steward.conf
build.sbt

This downgrades the logstash library as introducing the latest version causes a build error: 
```
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* com.gu:simple-configuration-core_2.13:2.0.0 (early-semver) is selected over 1.5.7
[error] 	    +- com.gu:mobile-logstash-encoder_2.13:1.1.9          (depends on 2.0.0)
[error] 	    +- com.gu:simple-configuration-ssm_2.13:1.5.7         (depends on 1.5.7)
```
-   [ ] [Colour …

Downgrade logstash

---

notificationworkerlambda/cdk/yarn.lock

This updates the version of micromatch in the yarn.lock to ensure we are using a version which has a vulnerability patch as suggested by the snyk console. 

Specificy micromatch version directly

---

notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/package.json
notificationworkerlambda/cdk/yarn.lock

Reverts guardian/mobile-n10n#1277 as we're confident this library bump wasn't the reason for the notifications issues

Revert "Revert "Bump @guardian/cdk from 59.1.0 to 59.2.1 in /notificationworkerlambda/cdk""

---

build.sbt

Reverts guardian/mobile-n10n#1279 since we've found out that the set of Snyk upgrades did not cause the notifications issues

Revert "Revert AWS dependency updates"

---

notification/test/notification/controllers/MainSpec.scala

Add tests for adding or removing a breaking news topic, in relation to #971 and #1285

Add tests for adding/removing a breaking news notification topic

---

notificationworkerlambda/cdk/lib/__snapshots__/senderworker.test.ts.snap
notificationworkerlambda/cdk/package.json
notificationworkerlambda/cdk/yarn.lock

This is a fork of this PR https://github.com/guardian/mobile-n10n/pull/1280 to upgrade the @guardian/cdk version and update the snapshats so that the CI tests can still pass

Ld/dependabot/npm and yarn/notificationworkerlambda/cdk/guardian/cdk 59.2.3

---

build.sbt

This upgrades the protobuf libraries as the current version had a vulnerability detected in Snyk

Upgrade the protobuf libraries

---

.github/workflows/event-consumer.yml
.github/workflows/fake-breaking-news.yml
.github/workflows/football.yml
.github/workflows/notification-worker-lambdas.yml
.github/workflows/notification.yml
.github/workflows/registration.yml
.github/workflows/report-extractor.yml
.github/workflows/report.yml
.github/workflows/schedule-lambda.yml
.github/workflows/slo-monitor.yml

This adds https://github.com/guardian/setup-scala/ to make sbt available in the github actions env

Use scala set up

---

build.sbt

This upgrades the version of netty in response to a security notification: https://github.com/advisories/GHSA-4g8c-wm8x-jfhw

Upgrade netty

---

build.sbt

This removes the netty library from notification worker lambda because an [upgrade](https://github.com/guardian/mobile-n10n/pull/1445) caused our service to break. Since netty is pulled in by the pushy library, we will use their version of netty so to avoid getting version conflicts
Deployed to CODE and tested that notifications send on iOS Devices
-   [ ] [The change doesn't use only colour to …

Remove netty from common

---

docs/architecture/03-postgresql-upgrade.md

This pull request fixes the syntax we use on the mermaid diagrams in the documentation.
I think the incorrect syntax on minute ("min") worked previously, maybe because the github was more lenient on the syntax.
Before
After
It changes the documentation only.

Fix the mermaid diagram of the doc
